(function(){
'use strict';
const root=document.getElementById('myProfileRoot');if(!root)return;
const API='/api/portal',CSRF_KEY='ea_portal_csrf',CURSOR_KEY='ea_portal_notification_cursor';
const SECURE_PORTAL_URL='https://project-ea-student-portal-staging.pages.dev/#my-profile';
const state={profile:null,workspace:null,account:null,csrf:sessionStorage.getItem(CSRF_KEY)||'',view:'overview',requestRows:[],selectedDay:null,selectedRecipient:null,poll:null,socket:null,sheetOpener:null};
let chatRoom='general',chatRows=[],chatTimer=null;
const h=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const monthLabel=v=>{const d=new Date(v+'-01T00:00:00');return Number.isNaN(d.valueOf())?v:d.toLocaleDateString(undefined,{month:'long',year:'numeric'});};
async function api(path,options={}){const headers=new Headers(options.headers||{});if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(options.method&&options.method!=='GET'&&state.csrf)headers.set('X-Portal-CSRF',state.csrf);const response=await fetch(API+path,{...options,headers,credentials:'include',cache:'no-store'});const data=await response.json().catch(()=>({success:false,error:'invalid_response'}));if(!response.ok||!data.success){const error=new Error(data.error||`HTTP ${response.status}`);error.status=response.status;throw error;}return data;}
function notice(message,error=false){const node=root.querySelector('[data-profile-alert]');if(!node)return;node.className='profile-alert'+(error?' error':'');node.textContent=message;node.hidden=!message;}
function serviceUnavailable(){root.innerHTML=`<div class="profile-auth"><div class="profile-kicker">Secure student portal</div><h2>My Profile is hosted separately for now</h2><p>The public site cannot connect to the secure profile service. This is not a wrong-password error, and your activated account does not need a new password.</p><p><a class="profile-btn" href="${SECURE_PORTAL_URL}" target="_blank" rel="noopener noreferrer">Open secure My Profile</a></p><p>Use the individual roll number and password you created during activation. This opens a separate Cloudflare tab; the public site stays open here.</p></div>`;}
function authScreen(mode='login'){
  const staff=mode.startsWith('staff-'),usingCode=mode!=='login'&&mode!=='staff-login',reset=mode==='reset'||mode==='staff-reset';
  root.innerHTML=`<div class="profile-auth"><div class="profile-kicker">Secure ${staff?'staff':'student'} portal</div><h2>My Profile</h2><p>${staff?'Use the staff activation code issued by Admin. Your LAN password is separate from this portal password.':'Your private daily scores and requests use a separate secure account. The older public scoreboard login does not unlock this page.'}</p><div class="profile-auth-switch"><button type="button" class="profile-btn ${staff?'secondary':''}" data-auth-mode="login">Student</button><button type="button" class="profile-btn ${staff?'':'secondary'}" data-auth-mode="staff-login">Teacher / Admin</button></div><div class="profile-auth-switch"><button type="button" class="profile-btn ${usingCode?'secondary':''}" data-auth-mode="${staff?'staff-login':'login'}">Sign in</button><button type="button" class="profile-btn ${usingCode?'':'secondary'}" data-auth-mode="${staff?'staff-activate':'activate'}">Activate account</button></div><div class="profile-alert" data-profile-alert hidden></div>${usingCode?`<p>${reset?'Ask the academy Admin for a one-use reset code. It expires after 24 hours.':'Enter the one-use code given to you by Admin.'}</p><form class="profile-form" data-activate><label>${reset?'Reset code':'Activation code'}<input name="activation_token" autocomplete="one-time-code" required></label><label>${reset?'New password':'Create password'}<input name="password" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></label><small>Use at least 6 characters, including a letter and a number.</small><button class="profile-btn" type="submit">${reset?'Reset password':'Activate secure account'}</button></form>`:`<form class="profile-form" data-login><label>${staff?'Staff login ID':'Roll number'}<input name="login_id" autocomplete="username" autocapitalize="characters" required></label><label>Portal password<input name="password" type="password" autocomplete="current-password" required></label><label>Device name<input name="device_label" maxlength="120" value="${h(navigator.platform||'Device')}"></label><button class="profile-btn" type="submit">Open My Profile</button></form><p><button type="button" class="profile-btn secondary" data-auth-mode="${staff?'staff-reset':'reset'}">Forgot password?</button></p>`}</div>`;
  root.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>authScreen(button.dataset.authMode));
  root.querySelector('[data-login]')?.addEventListener('submit',event=>login(event,staff));
  root.querySelector('[data-activate]')?.addEventListener('submit',event=>activate(event,staff));
}
async function login(event,staff=false){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]');button.disabled=true;notice('Signing in…');try{const data=await api(staff?'/auth/staff/login':'/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.csrf=data.csrf_token;sessionStorage.setItem(CSRF_KEY,state.csrf);state.account=data.account;await loadProfile();}catch(error){if(error.status===503||error.message==='origin_not_allowed'){serviceUnavailable();return;}notice(error.status===401?'Sign in failed. Check your login ID and portal password.':'The secure profile service could not be reached. Please retry shortly.',true);button.disabled=false;}}
async function activate(event,staff=false){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]');button.disabled=true;notice('Saving password…');try{const data=await api(staff?'/auth/staff/activate':'/auth/activate',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.csrf=data.csrf_token;sessionStorage.setItem(CSRF_KEY,state.csrf);state.account=data.account;await loadProfile();}catch(error){notice(error.message,true);button.disabled=false;}}
async function bootstrap(){try{const me=await api('/auth/me');state.account=me.account;const token=await api('/auth/csrf');state.csrf=token.csrf_token;sessionStorage.setItem(CSRF_KEY,state.csrf);await loadProfile();}catch(error){stopDelivery();if(error.status===503||error.message==='origin_not_allowed')serviceUnavailable();else authScreen('login');}}
async function loadProfile(){root.innerHTML='<div class="profile-auth"><h2>Loading My Profile…</h2></div>';try{if(state.account?.kind==='staff'){state.workspace=(await api('/me/workspace')).workspace;state.view='desk';renderStaffShell();return;}state.profile=(await api('/me/profile')).profile;state.workspace=await api('/me/workspace').then(data=>data.workspace).catch(()=>null);renderShell();await loadRequests(false);startDelivery();}catch(error){if(error.status===401){authScreen('login');return;}root.innerHTML=`<div class="profile-auth"><h2>Profile temporarily unavailable</h2><p>${h(error.message)}</p><button class="profile-btn" data-retry>Retry</button></div>`;root.querySelector('[data-retry]').onclick=bootstrap;}}
function renderShell(){const p=state.profile,o=p.overview||{};root.innerHTML=`<div class="profile-shell"><header class="profile-hero"><div><div class="profile-kicker">Private student record</div><h2>${h(o.name||'My Profile')}</h2><div class="profile-hero-meta">${h(o.roll)} · Class ${h(o.class||'—')} · ${h(o.group||'No group')}</div></div><button class="profile-btn secondary" data-profile-logout>Sign out</button></header><div class="profile-body"><div class="profile-subtabs"><button data-view="overview">Overview</button><button data-view="months">Monthly Scoresheets</button><button data-view="current">This Month</button><button data-view="requests">My Requests</button>${state.workspace?.posts?.length?'<button data-view="duties">My Duties</button>':''}${state.workspace?.chat_rooms?.length?'<button data-view="chat">Community Chat</button>':''}<button data-view="sessions">Devices</button></div><div class="profile-alert" data-profile-alert hidden></div><div data-profile-view></div></div></div><div class="profile-sheet" data-profile-sheet role="dialog" aria-modal="true" aria-label="Day actions"><div class="profile-sheet-card" data-profile-sheet-card></div></div>`;root.querySelector('[data-profile-logout]').onclick=logout;root.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;renderView();});root.querySelector('[data-profile-sheet]').onclick=event=>{if(event.target===event.currentTarget)closeSheet();};renderView();}
function renderStaffShell(){const w=state.workspace||{},person=w.identity||{};root.innerHTML=`<div class="profile-shell"><header class="profile-hero"><div><div class="profile-kicker">Private ${h(person.role||'staff')} workspace</div><h2>${h(person.login_id||'My Profile')}</h2><div class="profile-hero-meta">${h(label(person.role||'Staff'))} · Account verified ${h(w.verified_at?new Date(w.verified_at).toLocaleString():'—')}</div></div><button class="profile-btn secondary" data-profile-logout>Sign out</button></header><div class="profile-body"><div class="profile-subtabs"><button data-view="desk">Duty Desk</button>${w.chat_rooms?.length?'<button data-view="chat">Chat Monitor</button>':''}<button data-view="sessions">Devices</button></div><div class="profile-alert" data-profile-alert hidden></div><div data-profile-view></div></div></div>`;root.querySelector('[data-profile-logout]').onclick=logout;root.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;renderView();});renderView();}
function view(){return root.querySelector('[data-profile-view]');}function sheet(){return root.querySelector('[data-profile-sheet-card]');}
function openSheet(){const overlay=root.querySelector('[data-profile-sheet]');if(!overlay)return;if(!overlay.classList.contains('open'))state.sheetOpener=document.activeElement;overlay.classList.add('open');document.body.classList.add('profile-dialog-open');sheet().scrollTop=0;sheet().querySelector('[data-close]')?.focus();}
function closeSheet(){root.querySelector('[data-profile-sheet]')?.classList.remove('open');document.body.classList.remove('profile-dialog-open');state.sheetOpener?.focus?.();state.sheetOpener=null;}
document.addEventListener('keydown',event=>{const overlay=root.querySelector('[data-profile-sheet].open');if(!overlay)return;if(event.key==='Escape'){event.preventDefault();closeSheet();return;}if(event.key!=='Tab')return;const focusable=[...sheet().querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(node=>node.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
function renderView(){if(state.view!=='chat'&&chatTimer){clearInterval(chatTimer);chatTimer=null;}root.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view));if(state.view==='overview')renderOverview();else if(state.view==='months')renderMonths();else if(state.view==='current')renderCurrent();else if(state.view==='requests')renderRequests();else if(state.view==='duties')renderDuties();else if(state.view==='desk')renderStaffDesk();else if(state.view==='chat')renderChat();else renderSessions();}
function renderDuties(){const posts=state.workspace?.posts||[];view().innerHTML=`<h3>My active posts</h3><div class="profile-list">${posts.map(post=>`<div class="profile-card"><small>${h(post.scope?.kind==='academy'?'Academy':`${label(post.scope?.kind)} ${post.scope?.value||''}`)}</small><strong>${h(post.label)}</strong><p>${h(post.starts_on||'—')} to ${h(post.ends_on||'current')}</p></div>`).join('')}</div><p class="profile-duty-note">Your post details are shown here. Decisions and records are opened from their authorized workspaces.</p>`;}
function renderStaffDesk(){const w=state.workspace||{};view().innerHTML=`<h3>${h(label(w.identity?.role||'Staff'))} workspace</h3><div class="profile-grid">${(w.areas||[]).map(area=>`<div class="profile-card"><small>Area</small><strong>${h(area)}</strong></div>`).join('')}</div><p class="profile-duty-note">Use the LAN workspace for case decisions while cloud review tools are being introduced.</p>`;}
function renderOverview(){const o=state.profile.overview||{},current=(state.profile.months||[]).find(row=>row.month===state.profile.current_month);view().innerHTML=`<div class="profile-grid"><div class="profile-card"><small>Current official total</small><strong>${h(current?.official_total??'—')}</strong></div><div class="profile-card"><small>Stars</small><strong>${h(o.stars||0)}</strong></div><div class="profile-card"><small>Veto balance</small><strong>${h(o.veto_balance||0)}</strong></div><div class="profile-card"><small>Active months</small><strong>${h((state.profile.months||[]).length)}</strong></div></div><div class="profile-card" style="margin-top:14px"><small>Last verified</small><strong style="font-size:1rem">${h(new Date(state.profile.produced_at).toLocaleString())}</strong><p>Formula ${h(state.profile.formula_version)} · source revision ${h(state.profile.source_revision)}.</p></div>`;}
function components(row){return Object.entries(row.components||{}).map(([key,value])=>`<div class="profile-card"><small>${h(label(key))}</small><strong>${h(value??'—')}</strong></div>`).join('');}
function renderMonths(){const rows=(state.profile.months||[]).slice().reverse();view().innerHTML=`<div class="profile-months">${rows.map(row=>`<button class="profile-month" data-month="${h(row.month)}"><span><strong>${h(monthLabel(row.month))}</strong><small> · ${h(row.entry_count||0)} entries · Roll ${h(row.historical_roll||'—')}</small></span><strong>${h(row.official_total??'—')}</strong></button>`).join('')||'<p>No verified active months are available.</p>'}</div><div data-month-detail></div>`;view().querySelectorAll('[data-month]').forEach(button=>button.onclick=()=>loadMonth(button.dataset.month));}
async function loadMonth(month){const target=view().querySelector('[data-month-detail]');target.innerHTML='<p>Loading scoresheet…</p>';try{const detail=(await api('/me/profile/months/'+encodeURIComponent(month))).profile.month;target.innerHTML=`<div class="profile-card" style="margin-top:14px"><h3>${h(monthLabel(month))} · Total ${h(detail.official_total??'—')}</h3><div class="profile-breakdown">${components(detail)}</div></div>`;}catch(error){target.innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}}
function renderCurrent(){const detail=state.profile.current_month_detail;if(!detail){view().innerHTML='<p>The current month is not active for this account.</p>';return;}view().innerHTML=`<div class="profile-card"><small>${h(monthLabel(detail.month))}</small><strong>Official total ${h(detail.official_total??'—')}</strong><div class="profile-breakdown">${components(detail)}</div></div><h3>Daily view</h3><div class="profile-days">${(detail.days||[]).map(day=>`<button class="profile-day ${day.future?'future':''} ${day.has_record?'has-record':''}" data-day="${h(day.date)}" ${day.future?'disabled':''}><strong>${h(Number(day.date.slice(-2)))}</strong><span>${day.recorded_total==null?'—':h(day.recorded_total)}</span></button>`).join('')}</div><p style="color:var(--muted);font-size:12px">Tap a day to review entries or send a tracked request to Admin.</p>`;view().querySelectorAll('[data-day]').forEach(button=>button.onclick=()=>openDay(button.dataset.day));}
function openDay(date){const day=state.profile.current_month_detail.days.find(row=>row.date===date);state.selectedDay=day;state.selectedRecipient=null;const entries=(day.entries||[]).map(entry=>`<div class="profile-entry"><strong>${h(entry.points)} points · ${h(entry.stars)} stars</strong><div>${h(entry.note||'No note')}</div></div>`).join('')||'<p>No score entry recorded for this day.</p>';const actions=[];if(day.actions?.request_missing_score)actions.push('<button class="profile-btn" data-request-kind="missing_score">Request score</button>');if(day.actions?.report_incorrect_entry)actions.push('<button class="profile-btn secondary" data-request-kind="incorrect_entry">Report incorrect entry</button>');if(day.actions?.request_transfer)actions.push('<button class="profile-btn secondary" data-request-kind="transfer_request">Request transfer</button>');sheet().innerHTML=`<div class="profile-sheet-head"><div><div class="profile-kicker">${h(date)}</div><h3>Day record</h3></div><button class="profile-close" data-close aria-label="Close">✕</button></div>${entries}<div class="profile-actions">${actions.join('')}</div><div data-day-form></div>`;sheet().querySelector('[data-close]').onclick=closeSheet;sheet().querySelectorAll('[data-request-kind]').forEach(button=>button.onclick=()=>renderRequestForm(button.dataset.requestKind));openSheet();}
function renderRequestForm(kind){const day=state.selectedDay,entries=day.entries||[];const entryField=kind==='incorrect_entry'?`<label>Entry<select name="entry">${entries.map((entry,index)=>`<option value="${index}">${h(entry.points)} points · ${h(entry.note)}</option>`).join('')}</select></label>`:'';const pointsField=kind==='missing_score'?'<label>Expected points, if known<input name="claimed_points" type="number" step="1"></label>':'';const transferFields=kind==='transfer_request'?'<label>Find recipient<input data-recipient-search placeholder="Roll number or name" autocomplete="off"></label><div class="profile-recipient-results" data-recipient-results></div><label>Transfer type<select name="transfer_type"><option value="points">Points</option><option value="stars">Stars</option></select></label><label>Amount<input name="amount" type="number" min="1" max="50" required></label>':'';sheet().querySelector('[data-day-form]').innerHTML=`<form class="profile-form" data-request-form><h3>${h(label(kind))}</h3>${entryField}${pointsField}${transferFields}<label>Explain the request<textarea name="message" maxlength="2000" required></textarea></label><button class="profile-btn" type="submit">Send to Admin</button></form>`;const form=sheet().querySelector('[data-request-form]');form.onsubmit=event=>submitRequest(event,kind);const search=form.querySelector('[data-recipient-search]');if(search)search.oninput=debounce(()=>searchRecipients(search.value),250);}
async function searchRecipients(query){const target=sheet().querySelector('[data-recipient-results]');state.selectedRecipient=null;if(query.trim().length<2){target.innerHTML='';return;}try{const data=await api('/me/transfer-recipients?q='+encodeURIComponent(query));target.innerHTML=data.recipients.map(row=>`<button type="button" class="profile-recipient" data-recipient="${h(row.student_id)}"><strong>${h(row.login_id)}</strong> · ${h(row.display_name)} · Class ${h(row.class_label||'—')}</button>`).join('')||'<small>No active recipient found.</small>';target.querySelectorAll('[data-recipient]').forEach(button=>button.onclick=()=>{state.selectedRecipient=data.recipients.find(row=>String(row.student_id)===button.dataset.recipient);target.querySelectorAll('button').forEach(item=>item.classList.toggle('selected',item===button));});}catch(error){target.innerHTML=`<small>${h(error.message)}</small>`;}}
async function submitRequest(event,kind){event.preventDefault();const form=event.currentTarget,data=new FormData(form),day=state.selectedDay,payload={kind,target_date:day.date,message:String(data.get('message')||''),client_request_id:crypto.randomUUID(),context_version:state.profile.current_month_detail.content_version};if(kind==='missing_score'&&data.get('claimed_points')!=='')payload.claimed_points=Number(data.get('claimed_points'));if(kind==='incorrect_entry'){const entry=day.entries[Number(data.get('entry'))];payload.target_entry_ref=entry.entry_ref;payload.target_entry_digest=entry.content_digest;}if(kind==='transfer_request'){if(!state.selectedRecipient){notice('Select a recipient first.',true);return;}payload.transfer={recipient_student_id:String(state.selectedRecipient.student_id),transfer_type:String(data.get('transfer_type')),amount:Number(data.get('amount'))};}const button=form.querySelector('button[type=submit]');button.disabled=true;try{await api('/me/requests',{method:'POST',body:JSON.stringify(payload)});closeSheet();state.view='requests';await loadRequests();notice('Request sent. Admin replies will appear here.');}catch(error){notice(error.message,true);button.disabled=false;}}
async function loadRequests(render=true){try{state.requestRows=(await api('/me/requests')).requests||[];if(render&&state.view==='requests')renderRequests();}catch(error){if(render)notice(error.message,true);}}
function renderRequests(){view().innerHTML=`<div class="profile-list">${state.requestRows.map(row=>`<button class="profile-request" data-request="${h(row.request_id)}"><span class="profile-request-head"><strong>${h(label(row.kind))} · ${h(row.target_date)}</strong><span class="profile-status">${h(label(row.status))}</span></span><small>${h(row.message)}</small></button>`).join('')||'<p>No requests yet. Tap a current-month day to create one.</p>'}</div>`;view().querySelectorAll('[data-request]').forEach(button=>button.onclick=()=>openRequest(button.dataset.request));}
async function openRequest(id){sheet().innerHTML='<div class="profile-sheet-head"><h3>Loading conversation…</h3><button class="profile-close" data-close aria-label="Close">✕</button></div>';sheet().querySelector('[data-close]').onclick=closeSheet;openSheet();try{const data=await api('/me/requests/'+id+'/events');if(!root.querySelector('[data-profile-sheet].open'))return;sheet().innerHTML=`<div class="profile-sheet-head"><h3>Request conversation</h3><button class="profile-close" data-close aria-label="Close">✕</button></div><div class="profile-timeline">${data.events.map(event=>`<div class="profile-event"><strong>${h(label(event.event_type))}</strong><div>${h(event.payload?.message||event.payload?.reason||'Status updated')}</div><small>${h(new Date(event.created_at).toLocaleString())} · ${h(event.actor_type)}</small></div>`).join('')}</div><form class="profile-form" data-message-form><label>Reply<textarea name="message" maxlength="2000" required></textarea></label><button class="profile-btn" type="submit">Send reply</button></form>`;sheet().querySelector('[data-close]').onclick=closeSheet;sheet().querySelector('[data-close]').focus();sheet().querySelector('[data-message-form]').onsubmit=event=>sendMessage(event,id);}catch(error){if(!root.querySelector('[data-profile-sheet].open'))return;sheet().innerHTML=`<div class="profile-alert error">${h(error.message)}</div><button class="profile-btn" data-close>Close</button>`;sheet().querySelector('[data-close]').onclick=closeSheet;sheet().querySelector('[data-close]').focus();}}
async function sendMessage(event,id){event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await api('/me/requests/'+id+'/events',{method:'POST',body:JSON.stringify({message:new FormData(event.currentTarget).get('message'),client_message_id:crypto.randomUUID()})});await openRequest(id);await loadRequests(false);}catch(error){notice(error.message,true);button.disabled=false;}}
async function renderSessions(){view().innerHTML='<p>Loading signed-in devices…</p>';try{const data=await api('/auth/sessions');view().innerHTML=`<div class="profile-list">${data.sessions.map(row=>`<div class="profile-request"><span class="profile-request-head"><strong>${h(row.device_label||'Unnamed device')}</strong>${row.session_id===data.current_session_id?'<span class="profile-status">This device</span>':`<button class="profile-btn warn" data-revoke="${h(row.session_id)}">Sign out</button>`}</span><small>Signed in ${h(new Date(row.created_at).toLocaleString())}</small></div>`).join('')}</div>`;view().querySelectorAll('[data-revoke]').forEach(button=>button.onclick=()=>revokeSession(button.dataset.revoke));}catch(error){view().innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}}
async function revokeSession(id){try{await api('/auth/sessions/'+id,{method:'DELETE'});renderSessions();}catch(error){notice(error.message,true);}}
async function logout(){try{await api('/auth/logout',{method:'POST'});}catch{}sessionStorage.removeItem(CSRF_KEY);state.csrf='';state.profile=null;state.workspace=null;state.account=null;stopDelivery();authScreen('login');}
function startDelivery(){stopDelivery();pollNotifications();state.poll=setInterval(pollNotifications,20000);try{const protocol=location.protocol==='https:'?'wss:':'ws:';state.socket=new WebSocket(protocol+'//'+location.host+API+'/me/notifications/socket');state.socket.onmessage=()=>pollNotifications();}catch{}}
function stopDelivery(){if(chatTimer){clearInterval(chatTimer);chatTimer=null;}if(state.poll)clearInterval(state.poll);state.poll=null;if(state.socket){try{state.socket.close();}catch{}}state.socket=null;}
async function pollNotifications(){try{const after=sessionStorage.getItem(CURSOR_KEY)||'0',data=await api('/me/notifications?after='+encodeURIComponent(after));sessionStorage.setItem(CURSOR_KEY,String(data.cursor||after));if(data.notifications?.length){await loadRequests(false);if(state.view==='requests')renderRequests();notice(`${data.notifications.length} request update${data.notifications.length===1?'':'s'} received.`);}}catch{}}
function debounce(fn,wait){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),wait);};}
function renderChat(){
  const rooms=state.workspace?.chat_rooms||[];
  if(!rooms.includes(chatRoom))chatRoom=rooms[0]||'general';
  view().innerHTML=`<div class="profile-chat-head"><div><h3>${h(chatRoom==='council'?'Student Council':'General Chat')}</h3><small>Messages are monitored under the academy rules.</small></div><div class="profile-actions">${rooms.map(room=>`<button type="button" class="profile-btn ${room===chatRoom?'':'secondary'}" data-chat-room="${h(room)}">${h(room==='council'?'Student Council':'General')}</button>`).join('')}</div></div><div class="profile-list" data-chat-messages aria-live="polite"><p>Loading messages…</p></div><div class="profile-alert" data-chat-error hidden></div>${state.account?.kind==='staff'?'':`<form class="profile-form" data-chat-form><label>Message<textarea name="message" maxlength="1500" required></textarea></label><button class="profile-btn" type="submit">Send message</button></form>`}`;
  view().querySelectorAll('[data-chat-room]').forEach(button=>button.onclick=()=>{chatRoom=button.dataset.chatRoom;chatRows=[];renderChat();});
  view().querySelector('[data-chat-form]')?.addEventListener('submit',sendChat);
  loadChat();
  if(!chatTimer)chatTimer=setInterval(()=>{if(state.view==='chat')loadChat();},10000);
}
async function loadChat(){
  const room=chatRoom;
  try{
    const data=await api('/chat/'+room+'/messages');
    if(state.view!=='chat'||chatRoom!==room)return;
    chatRows=data.messages||[];
    const target=view().querySelector('[data-chat-messages]');
    target.innerHTML=chatRows.map(row=>`<article class="profile-chat-message ${row.pinned?'pinned':''} ${row.highlighted?'highlighted':''}"><div class="profile-chat-meta"><strong>${h(row.login_id)}</strong><small>${h(new Date(row.created_at).toLocaleString())}</small>${row.pinned?'<span class="profile-status">Pinned</span>':''}${row.highlighted?'<span class="profile-status">Highlighted</span>':''}</div><p>${row.hidden?'<em>Message hidden by a moderator.</em>':h(row.body)}</p>${row.can_moderate?`<div class="profile-actions"><button type="button" class="profile-btn secondary" data-chat-action="hide" data-chat-id="${h(row.message_id)}">Hide</button>${data.moderator!=='co_leader'?`<button type="button" class="profile-btn secondary" data-chat-action="${row.pinned?'unpin':'pin'}" data-chat-id="${h(row.message_id)}">${row.pinned?'Unpin':'Pin'}</button><button type="button" class="profile-btn secondary" data-chat-action="${row.highlighted?'unhighlight':'highlight'}" data-chat-id="${h(row.message_id)}">${row.highlighted?'Remove highlight':'Highlight'}</button>`:''}<button type="button" class="profile-btn secondary" data-chat-restrict="${h(row.student_id)}">Restrict chat</button></div>`:''}</article>`).join('')||'<p>No messages yet.</p>';
    target.querySelectorAll('[data-chat-action]').forEach(button=>button.onclick=()=>moderateChat(button.dataset.chatId,button.dataset.chatAction));
    target.querySelectorAll('[data-chat-restrict]').forEach(button=>button.onclick=()=>restrictChat(button.dataset.chatRestrict));
    view().querySelector('[data-chat-error]').hidden=true;
  }catch(error){
    if(state.view!=='chat'||chatRoom!==room)return;
    const alert=view().querySelector('[data-chat-error]');alert.textContent=error.message;alert.hidden=false;
    if(error.status===403){view().querySelector('[data-chat-messages]').innerHTML='<p>Chat access is currently unavailable.</p>';view().querySelector('[data-chat-form]')?.remove();}
  }
}
async function sendChat(event){
  event.preventDefault();
  const form=event.currentTarget,button=form.querySelector('button[type=submit]'),message=String(new FormData(form).get('message')||'').trim();
  if(!message)return;
  button.disabled=true;
  try{await api('/chat/'+chatRoom+'/messages',{method:'POST',body:JSON.stringify({message,client_message_id:crypto.randomUUID()})});form.reset();await loadChat();}
  catch(error){notice(error.message,true);}
  finally{button.disabled=false;}
}
async function moderateChat(id,action){
  const reason=action==='hide'?prompt('Reason for hiding this message:'):'';
  if(action==='hide'&&!reason)return;
  try{await api('/chat/'+chatRoom+'/messages/'+encodeURIComponent(id)+'/moderate',{method:'POST',body:JSON.stringify({action,reason})});await loadChat();}
  catch(error){notice(error.message,true);}
}
async function restrictChat(studentId){
  const duration=prompt('Restrict chat for how many hours? Leader: up to 24; Co-Leader: 1; Admin: up to 720.','1');
  if(duration===null)return;
  const reason=prompt('Reason for this chat restriction:');
  if(!reason)return;
  try{await api('/chat/restrictions',{method:'POST',body:JSON.stringify({student_id:studentId,duration_hours:Number(duration),reason})});notice('Chat restriction recorded.');await loadChat();}
  catch(error){notice(error.message,true);}
}
window.EA_PROFILE_APP={open:bootstrap};if(location.hash.toLowerCase()==='#my-profile')bootstrap();else authScreen('login');
})();
