(function(){
'use strict';
const root=document.getElementById('myProfileRoot');if(!root)return;
const API='/api/portal',CSRF_KEY='ea_portal_csrf',CURSOR_KEY='ea_portal_notification_cursor';
const SECURE_PORTAL_URL='https://project-ea-student-portal-staging.pages.dev/#my-profile';
const state={profile:null,workspace:null,account:null,csrf:sessionStorage.getItem(CSRF_KEY)||'',view:'overview',requestRows:[],selectedDay:null,selectedRecipient:null,poll:null,socket:null,sheetOpener:null};
let chatRoom='general',chatRows=[],chatTimer=null,sessionGeneration=0;
let notificationBusy=false,chatBusy=false,deliveryActive=false,socketReconnect=null,nextNotificationCheck=0,quotaRetryAt=0;
const h=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const monthLabel=v=>{const d=new Date(v+'-01T00:00:00');return Number.isNaN(d.valueOf())?v:d.toLocaleDateString(undefined,{month:'long',year:'numeric'});};
async function api(path,options={}){if(Date.now()<quotaRetryAt){const error=new Error('database_daily_quota_exceeded');error.status=503;throw error;}const generation=sessionGeneration;const headers=new Headers(options.headers||{});if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(options.method&&options.method!=='GET'&&state.csrf)headers.set('X-Portal-CSRF',state.csrf);const response=await fetch(API+path,{...options,headers,credentials:'include',cache:'no-store'});const data=await response.json().catch(()=>({success:false,error:'invalid_response'}));if(generation!==sessionGeneration)throw new Error('Session changed; reopen My Profile.');if(!response.ok||!data.success){const error=new Error(data.error||`HTTP ${response.status}`);error.status=response.status;if(data.error==='database_daily_quota_exceeded'){quotaRetryAt=Date.parse(data.retry_at)||Date.now()+300000;stopDelivery();serviceUnavailable(error);}throw error;}return data;}
function notice(message,error=false){const node=root.querySelector('[data-profile-alert]');if(!node)return;node.className='profile-alert'+(error?' error':'');node.textContent=message;node.hidden=!message;}
function serviceUnavailable(error){if(error?.message==='database_daily_quota_exceeded'||Date.now()<quotaRetryAt){root.innerHTML=`<div class="profile-auth"><h2>Daily cloud database allowance reached</h2><p>The secure service has reached its daily database allowance. Your password does not need changing.</p><p>Automatic retries are paused. Retry after ${h(new Date(quotaRetryAt).toLocaleString())}.</p><button class="profile-btn" data-quota-retry>Retry My Profile</button></div>`;root.querySelector('[data-quota-retry]').onclick=bootstrap;return;}root.innerHTML=`<div class="profile-auth"><div class="profile-kicker">Secure student portal</div><h2>My Profile is hosted separately for now</h2><p>The public site cannot connect to the secure profile service. This is not a wrong-password error, and your activated account does not need a new password.</p><p><a class="profile-btn" href="${SECURE_PORTAL_URL}" target="_blank" rel="noopener noreferrer">Open secure My Profile</a></p><p>Use the individual roll number and password you created during activation. This opens a separate Cloudflare tab; the public site stays open here.</p></div>`;}
function authScreen(mode='login'){
  const staff=mode.startsWith('staff-'),usingCode=mode!=='login'&&mode!=='staff-login',reset=mode==='reset'||mode==='staff-reset';
  root.innerHTML=`<div class="profile-auth"><div class="profile-kicker">Secure ${staff?'staff':'student'} portal</div><h2>My Profile</h2><p>${staff?'Use the staff activation code issued by Admin. Your LAN password is separate from this portal password.':'Your private daily scores and requests use a separate secure account. The older public scoreboard login does not unlock this page.'}</p><div class="profile-auth-switch"><button type="button" class="profile-btn ${staff?'secondary':''}" data-auth-mode="login">Student</button><button type="button" class="profile-btn ${staff?'':'secondary'}" data-auth-mode="staff-login">Teacher / Admin</button></div><div class="profile-auth-switch"><button type="button" class="profile-btn ${usingCode?'secondary':''}" data-auth-mode="${staff?'staff-login':'login'}">Sign in</button><button type="button" class="profile-btn ${usingCode?'':'secondary'}" data-auth-mode="${staff?'staff-activate':'activate'}">Activate account</button></div><div class="profile-alert" data-profile-alert hidden></div>${usingCode?`<p>${reset?'Ask the academy Admin for a one-use reset code. It expires after 24 hours.':'Enter the one-use code given to you by Admin.'}</p><form class="profile-form" data-activate><label>${reset?'Reset code':'Activation code'}<input name="activation_token" autocomplete="one-time-code" required></label><label>${reset?'New password':'Create password'}<input name="password" type="password" minlength="6" maxlength="128" autocomplete="new-password" required></label><small>Use at least 6 characters, including a letter and a number.</small><button class="profile-btn" type="submit">${reset?'Reset password':'Activate secure account'}</button></form>`:`<form class="profile-form" data-login><label>${staff?'Staff login ID':'Roll number'}<input name="login_id" autocomplete="username" autocapitalize="characters" required></label><label>Portal password<input name="password" type="password" autocomplete="current-password" required></label><label>Device name<input name="device_label" maxlength="120" value="${h(navigator.platform||'Device')}"></label><button class="profile-btn" type="submit">Open My Profile</button></form><p><button type="button" class="profile-btn secondary" data-auth-mode="${staff?'staff-reset':'reset'}">Forgot password?</button></p>`}</div>`;
  root.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>authScreen(button.dataset.authMode));
  root.querySelector('[data-login]')?.addEventListener('submit',event=>login(event,staff));
  root.querySelector('[data-activate]')?.addEventListener('submit',event=>activate(event,staff));
}
async function login(event,staff=false){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]');button.disabled=true;notice('Signing in…');try{const data=await api(staff?'/auth/staff/login':'/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.csrf=data.csrf_token;sessionStorage.setItem(CSRF_KEY,state.csrf);state.account=data.account;await loadProfile();}catch(error){if(error.status===503||error.message==='origin_not_allowed'){serviceUnavailable();return;}notice(error.status===401?'Sign in failed. Check your login ID and portal password.':'The secure profile service could not be reached. Please retry shortly.',true);button.disabled=false;}}
async function activate(event,staff=false){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]');button.disabled=true;notice('Saving password…');try{const data=await api(staff?'/auth/staff/activate':'/auth/activate',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});state.csrf=data.csrf_token;sessionStorage.setItem(CSRF_KEY,state.csrf);state.account=data.account;await loadProfile();}catch(error){notice(error.message,true);button.disabled=false;}}
async function bootstrap(){const generation=++sessionGeneration;try{const me=await api('/auth/me');state.account=me.account;state.lastLogin=me.session?.logged_in_at||null;const token=await api('/auth/csrf');state.csrf=token.csrf_token;sessionStorage.setItem(CSRF_KEY,state.csrf);await loadProfile();}catch(error){if(generation!==sessionGeneration)return;stopDelivery();if(error.status===503||error.message==='origin_not_allowed')serviceUnavailable();else authScreen('login');}}
async function loadProfile(){const generation=sessionGeneration;window.dispatchEvent(new CustomEvent('ea-portal-session',{detail:state.account}));root.innerHTML='<div class="profile-auth"><h2>Loading My Profile…</h2></div>';try{if(state.account?.kind==='staff'){state.workspace=(await api('/me/workspace')).workspace;state.view='desk';renderStaffShell();return;}state.profile=(await api('/me/profile')).profile;state.workspace=await api('/me/workspace').then(data=>data.workspace).catch(()=>null);if(Date.now()<quotaRetryAt){serviceUnavailable();return;}await loadPortraits();if(Date.now()<quotaRetryAt){serviceUnavailable();return;}renderShell();await loadRequests(false);if(generation===sessionGeneration)startDelivery();}catch(error){if(generation!==sessionGeneration)return;if(error.message==='database_daily_quota_exceeded'){serviceUnavailable(error);return;}if(error.status===401){authScreen('login');return;}root.innerHTML=`<div class="profile-auth"><h2>Profile temporarily unavailable</h2><p>${h(error.message)}</p><button class="profile-btn" data-retry>Retry</button></div>`;root.querySelector('[data-retry]').onclick=bootstrap;}}
function renderShell(){const p=state.profile,o=p.overview||{};root.innerHTML=`<div class="profile-shell"><header class="profile-hero"><div class="profile-person">${portraitHtml(state.account.student_id,o.name,true)}<div><div class="profile-kicker">Private student record</div><h2>${h(o.name||'My Profile')}</h2><div class="profile-hero-meta">${h(o.roll)} · Class ${h(o.class||'—')} · ${h(o.group||'No group')}</div></div></div><button class="profile-btn secondary" data-profile-logout>Sign out</button></header><div class="profile-body"><div class="profile-subtabs"><button data-view="overview">Overview</button><button data-view="months">Monthly Scoresheets</button><button data-view="current">This Month</button><button data-view="requests">My Requests</button>${state.workspace?.transfers_enabled?'<button data-view="transfers">Transfers & Banks</button>':''}${state.workspace?.cases_enabled?'<button data-view="cases">Proposals & Appeals</button>':''}${state.workspace?.instructions_enabled?'<button data-view="instructions">Instructions</button>':''}${(state.workspace?.posts?.length||state.workspace?.party_workspace_enabled)?'<button data-view="duties">My Duties</button>':''}${state.workspace?.chat_rooms?.length?'<button data-view="chat">Community Chat</button>':''}<button data-view="gallery">Gallery</button><button data-view="photos">Profile picture</button><button data-view="sessions">Devices</button></div><div class="profile-alert" data-profile-alert hidden></div><div data-profile-view></div></div></div><div class="profile-sheet" data-profile-sheet role="dialog" aria-modal="true" aria-label="Day actions"><div class="profile-sheet-card" data-profile-sheet-card></div></div>`;root.querySelector('[data-profile-logout]').onclick=logout;root.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;renderView();});root.querySelector('[data-profile-sheet]').onclick=event=>{if(event.target===event.currentTarget)closeSheet();};renderView();}
function renderStaffShell(){const w=state.workspace||{},person=w.identity||{};root.innerHTML=`<div class="profile-shell"><header class="profile-hero"><div><div class="profile-kicker">Private ${h(person.role||'staff')} workspace</div><h2>${h(person.login_id||'My Profile')}</h2><div class="profile-hero-meta">${h(label(person.role||'Staff'))} · Account verified ${h(w.verified_at?new Date(w.verified_at).toLocaleString():'—')}</div></div><button class="profile-btn secondary" data-profile-logout>Sign out</button></header><div class="profile-body"><div class="profile-subtabs"><button data-view="desk">Duty Desk</button>${w.cases_enabled?'<button data-view="cases">Review Inbox</button>':''}${w.instructions_enabled?'<button data-view="instructions">Instructions</button>':''}${w.chat_rooms?.length?'<button data-view="chat">Chat Monitor</button>':''}<button data-view="gallery">Gallery</button><button data-view="sessions">Devices</button></div><div class="profile-alert" data-profile-alert hidden></div><div data-profile-view></div></div></div>`;root.querySelector('[data-profile-logout]').onclick=logout;root.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;renderView();});renderView();}
function view(){return root.querySelector('[data-profile-view]');}function sheet(){return root.querySelector('[data-profile-sheet-card]');}
async function openSheet(){const overlay=root.querySelector('[data-profile-sheet]');if(!overlay)return;if(!overlay.classList.contains('open'))state.sheetOpener=document.activeElement;if(state.workspace?.audit_enabled&&!await recordUi('dialog_opened','profile-sheet'))return;overlay.classList.add('open');document.body.classList.add('profile-dialog-open');sheet().scrollTop=0;sheet().querySelector('[data-close]')?.focus();}
function closeSheet(){recordUi('dialog_closed','profile-sheet');root.querySelector('[data-profile-sheet]')?.classList.remove('open');document.body.classList.remove('profile-dialog-open');state.sheetOpener?.focus?.();state.sheetOpener=null;}
document.addEventListener('keydown',event=>{const overlay=root.querySelector('[data-profile-sheet].open');if(!overlay)return;if(event.key==='Escape'){event.preventDefault();closeSheet();return;}if(event.key!=='Tab')return;const focusable=[...sheet().querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(node=>node.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
async function renderView(){decorateGovernanceTabs();const requestedView=state.view;if((state.workspace?.audit_enabled&&!await recordUi('view_opened',requestedView))||state.view!==requestedView)return;if(state.view!=='chat'&&chatTimer){clearInterval(chatTimer);chatTimer=null;}root.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view));if(state.view==='gallery')renderGallery();else if(state.view==='photos')renderPhotoSettings();else if(state.view==='overview')renderOverview();else if(state.view==='months')renderMonths();else if(state.view==='current')renderCurrent();else if(state.view==='requests')renderRequests();else if(state.view==='transfers')renderTransfers();else if(state.view==='cases')renderCases();else if(state.view==='instructions')renderInstructions();else if(state.view==='my-party')renderMyParty();else if(state.view==='academy')renderAcademy();else if(state.view==='duties')renderDuties();else if(state.view==='audit')renderAudit();else if(state.view==='party-pacts')renderPartyPacts();else if(state.view==='desk')renderStaffDesk();else if(state.view==='chat')renderChat();else renderSessions();}
async function renderDuties(){
  const posts=state.workspace?.posts||[];
  view().innerHTML=`<h3>My active posts</h3><div class="profile-grid profile-posts">${posts.map(post=>`<div class="profile-card"><small>${h(post.scope?.kind==='academy'?'Academy':`${label(post.scope?.kind)} ${post.scope?.value||''}`)}</small><strong>${h(post.label)}</strong><p>${h(post.starts_on||'—')} to ${h(post.ends_on||'current')}</p></div>`).join('')}</div><div data-party-workspace></div>`;
  if(state.workspace?.duty_workspace_enabled){await loadDutyAreas();return;}
  if(!state.workspace?.party_workspace_enabled)return;
  try{
    const data=await api('/me/party-workspace');if(state.view!=='duties')return;
    const target=view().querySelector('[data-party-workspace]');
    target.innerHTML=(data.parties||[]).map(party=>`<section class="profile-card"><h3>${h(party.name)} · Party members</h3><div class="profile-list">${party.members.map(member=>`<div class="profile-duty-member">${portraitHtml(member.student_id,member.name||member.login_id)}<strong>${h(member.name||member.login_id)}</strong> · ${h(member.login_id)}<small> · ${h(label(member.designation))}</small></div>`).join('')||'<p>No current members.</p>'}</div>${party.posts.some(post=>post.key==='pp')?`<details class="profile-duty-compose"><summary>Assign responsibility and work</summary><form class="profile-form" data-party-assign><input type="hidden" name="acting_assignment_id" value="${h(party.posts.find(post=>post.key==='pp').assignment_id)}"><label>Member<select name="recipient_student_id">${party.members.map(member=>`<option value="${h(member.student_id)}">${h(member.name||member.login_id)} · ${h(member.login_id)}</option>`).join('')}</select></label><label>Internal responsibility<input name="role" maxlength="100" placeholder="For example, activity coordinator" required></label><label>Work and instructions<textarea name="work" minlength="10" maxlength="4000" required></textarea></label><label>Deadline, if applicable<input name="due_on" type="date"></label><button class="profile-btn" type="submit">Assign responsibility and work</button></form></details>`:''}</section>`).join('')+`<h3>Assigned work</h3><div class="profile-list">${(data.assignments||[]).map(row=>`<article class="profile-card"><small>${h(row.recipient_login_id)} · From ${h(row.issuer_label)}</small><h4>${h(row.role)}</h4><p>${h(row.work)}</p>${row.due_on?`<small>Due ${h(row.due_on)}</small>`:''}</article>`).join('')||'<p>No party work assigned yet.</p>'}</div>`;
    target.querySelectorAll('[data-party-assign]').forEach(form=>{
      form.oninput=()=>{delete form.dataset.clientId;};
      form.onsubmit=async event=>{
        event.preventDefault();const button=form.querySelector('button[type=submit]');form.dataset.clientId ||= crypto.randomUUID();button.disabled=true;
        try{await api('/me/party-workspace/assignments',{method:'POST',body:JSON.stringify({...Object.fromEntries(new FormData(form)),client_assignment_id:form.dataset.clientId})});await renderDuties();notice('Responsibility and work assigned.');}
        catch(error){notice(error.message,true);button.disabled=false;}
      };
    });
  }catch(error){if(state.view==='duties')view().querySelector('[data-party-workspace]').innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}
}
async function loadDutyAreas(){
  const target=view().querySelector('[data-party-workspace]');target.innerHTML='<p>Loading your duties and directory…</p>';
  try{
    const data=await api('/me/duty-workspace');if(state.view!=='duties')return;
    target.innerHTML=(data.areas||[]).map(area=>`<section class="profile-card"><h3>${h(area.post.label)} · ${h(area.post.scope.kind==='academy'?'Academy':label(area.post.scope.kind)+' '+area.post.scope.value)}</h3><div class="profile-list">${area.members.map(member=>`<div class="profile-duty-member">${portraitHtml(member.student_id,member.name||member.login_id)}<strong>${h(member.name||member.login_id)}</strong> · ${h(member.login_id)}${area.can_view_records?` <button class="profile-btn secondary" data-current-student="${h(member.student_id)}" data-assignment="${h(area.post.assignment_id)}">Current record</button>`:''}</div>`).join('')}</div><details class="profile-duty-compose"><summary>Assign a duty</summary><form class="profile-form" data-duty-assign><input type="hidden" name="acting_assignment_id" value="${h(area.post.assignment_id)}"><label>Student<select name="recipient_student_id">${area.members.map(member=>`<option value="${h(member.student_id)}">${h(member.name||member.login_id)} · ${h(member.login_id)}</option>`).join('')}</select></label><label>Responsibility<input name="role" maxlength="100" required></label><label>Work and instructions<textarea name="work" minlength="10" maxlength="4000" required></textarea></label><label>Deadline<input name="due_on" type="date"></label><button type="submit" class="profile-btn">Assign duty</button></form></details></section>`).join('')+`<h3>Assigned work</h3>${(data.assignments||[]).map(row=>`<article class="profile-card"><small>${h(row.recipient_login_id)} · ${h(row.acting_post?.label||row.issuer_label)}</small><h4>${h(row.role)}</h4><p>${h(row.work)}</p>${row.due_on?`<small>Due ${h(row.due_on)}</small>`:''}</article>`).join('')||'<p>No work assigned yet.</p>'}<div data-current-record></div>`;
    for(const area of data.areas||[]){if(area.post.key!=='rm')continue;
      const eligible=area.members.filter(member=>member.quota_eligible);
      target.insertAdjacentHTML('beforeend',`<section class="profile-card"><h3>Propose a quota change</h3><p>Admin must approve. Resource quotas use ₹; point-bank allowances use points. Leader, Co-Leader and LoP are excluded.</p><form class="profile-form" data-quota-propose><input type="hidden" name="acting_assignment_id" value="${h(area.post.assignment_id)}"><label>Student<select name="student_id">${eligible.map(member=>`<option value="${h(member.student_id)}">${h(member.name||member.login_id)} · ${h(member.login_id)}${member.quota_bank_id?' · GR bank available':''}</option>`).join('')}</select></label><label>Quota<select name="quota_kind"><option value="resource">Resource purchase quota (₹)</option><option value="bank">GR group monthly point-bank allowance</option></select></label><label>Proposed monthly allowance<input type="number" name="amount" min="0" max="10000" step="1" required></label><label>Reason<textarea name="reason" minlength="10" maxlength="4000" required></textarea></label><button type="submit" class="profile-btn">Send proposal to Admin</button></form></section>`);
    }
    target.querySelectorAll('[data-quota-propose]').forEach(form=>{form.oninput=()=>{delete form.dataset.clientId;};form.onsubmit=async event=>{
      event.preventDefault();const values=Object.fromEntries(new FormData(form)),button=form.querySelector('button[type=submit]');form.dataset.clientId ||= crypto.randomUUID();button.disabled=true;
      try{const result=await api('/cases',{method:'POST',body:JSON.stringify({kind:'proposal',title:'Monthly '+values.quota_kind+' quota change',body:values.reason,direct_admin:true,acting_assignment_id:values.acting_assignment_id,quota_request:{kind:values.quota_kind,student_id:values.student_id,amount:Number(values.amount)},client_case_id:form.dataset.clientId})});state.view='cases';await renderView();await openCase(result.case_id);notice('Quota proposal sent to Admin.');}catch(error){notice(error.message,true);button.disabled=false;}
    };});
    target.querySelectorAll('[data-duty-assign]').forEach(form=>{
      form.oninput=()=>{delete form.dataset.clientId;};
      form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]');form.dataset.clientId ||= crypto.randomUUID();button.disabled=true;try{await api('/me/duty-workspace/assignments',{method:'POST',body:JSON.stringify({...Object.fromEntries(new FormData(form)),client_assignment_id:form.dataset.clientId})});await loadDutyAreas();notice('Duty assigned.');}catch(error){notice(error.message,true);button.disabled=false;}};
    });
    let recordRequest=0;
    target.querySelectorAll('[data-current-student]').forEach(button=>{
      button.setAttribute('aria-expanded','false');
      button.onclick=async()=>{
        const request=++recordRequest;
        target.querySelectorAll('[data-inline-current-record]').forEach(node=>node.remove());
        target.querySelectorAll('[data-current-student]').forEach(node=>node.setAttribute('aria-expanded','false'));
        const panel=document.createElement('section');panel.className='profile-card profile-inline-record';panel.dataset.inlineCurrentRecord='';panel.tabIndex=-1;panel.setAttribute('aria-live','polite');
        panel.id='record-'+request;button.setAttribute('aria-controls',panel.id);button.setAttribute('aria-expanded','true');
        button.parentElement.insertAdjacentElement('afterend',panel);
        const close=()=>{if(request===recordRequest)recordRequest++;panel.remove();button.setAttribute('aria-expanded','false');button.removeAttribute('aria-controls');button.focus();};
        panel.innerHTML='<p>Loading current record…</p><button class="profile-btn secondary" data-record-close>Close record</button>';panel.querySelector('[data-record-close]').onclick=close;
        panel.scrollIntoView?.({behavior:'smooth',block:'nearest'});
        try{
          const data=await api('/me/students/'+encodeURIComponent(button.dataset.currentStudent)+'/current?assignment='+encodeURIComponent(button.dataset.assignment));
          if(state.view!=='duties'||!panel.isConnected||request!==recordRequest)return;
          const s=data.student,m=s.current_record;
          panel.innerHTML=`<div class="profile-sheet-head"><h4>${portraitHtml(s.student_id,s.name||s.login_id)}${h(s.name||s.login_id)} · ${h(s.login_id)}</h4><button class="profile-btn secondary" data-record-close>Close record</button></div><p>Class ${h(s.class)} · Group ${h(s.group)}${(s.posts||[]).length?' · '+h(s.posts.map(post=>post.label).join(', ')):''}</p>${m?`<strong>${h(monthLabel(m.month))} · Total ${h(m.official_total??'—')}</strong><details><summary>Score breakdown</summary><div class="profile-grid">${components(m)}</div></details><details><summary>Day records · ${(m.days||[]).filter(day=>day.attendance_status||day.has_record).length} days</summary><div class="profile-list">${(m.days||[]).filter(day=>day.attendance_status||day.has_record).map(day=>`<details class="profile-record-day ${Number(day.recorded_total)>0?'positive':Number(day.recorded_total)<0?'negative':''}"><summary><strong>${h(day.date)}</strong> · ${h(day.attendance_status||'No attendance mark')} · ${h(day.recorded_total??'—')} points</summary>${(day.entries||[]).map(entry=>`<p>${h(entry.points)} points · ${h(entry.stars??0)} stars<br>${h(entry.note||'No note')}</p>`).join('')||'<p>No recorded score entries.</p>'}</details>`).join('')}</div></details>`:'<p>Current-month record requires Admin review or is unavailable.</p>'}`;
          panel.querySelector('[data-record-close]').onclick=close;panel.focus({preventScroll:true});panel.scrollIntoView?.({behavior:'smooth',block:'nearest'});
        }catch(error){if(panel.isConnected&&request===recordRequest){panel.querySelector('p').textContent=error.message;panel.classList.add('error');}}
      };
    });
  }catch(error){if(state.view==='duties')target.innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}
}
function renderStaffDesk(){const w=state.workspace||{};view().innerHTML=`<h3>${h(label(w.identity?.role||'Staff'))} workspace</h3><div class="profile-grid">${(w.areas||[]).map(area=>`<div class="profile-card"><small>Area</small><strong>${h(area)}</strong></div>`).join('')}</div><p class="profile-duty-note">Use Review Inbox for cloud cases. Existing LAN records are reviewed in their LAN workspaces.</p>`;}
function renderOverview(){const o=state.profile.overview||{},current=(state.profile.months||[]).find(row=>row.month===state.profile.current_month);view().innerHTML=`<div class="profile-grid"><div class="profile-card"><small>Current official total</small><strong>${h(current?.official_total??'—')}</strong></div><div class="profile-card"><small>Stars</small><strong>${h(o.stars||0)}</strong></div><div class="profile-card"><small>Veto balance</small><strong>${h(o.veto_balance||0)}</strong></div><div class="profile-card"><small>Active months</small><strong>${h((state.profile.months||[]).length)}</strong></div></div><div class="profile-card" style="margin-top:14px"><small>Last logged in</small><strong style="font-size:1rem">${h(state.lastLogin?new Date(state.lastLogin).toLocaleString():'Unavailable')}</strong></div>`;}
function components(row){return Object.entries(row.components||{}).map(([key,value])=>`<div class="profile-card"><small>${h(label(key))}</small><strong>${h(value??'—')}</strong></div>`).join('');}
function renderMonths(){const rows=(state.profile.months||[]).slice().reverse();view().innerHTML=`<div class="profile-months">${rows.map(row=>`<button class="profile-month" data-month="${h(row.month)}"><span><strong>${h(monthLabel(row.month))}</strong><small> · ${h(row.entry_count||0)} entries · Roll ${h(row.historical_roll||'—')}</small></span><strong>${h(row.official_total??'—')}</strong></button>`).join('')||'<p>No verified active months are available.</p>'}</div><div data-month-detail></div>`;view().querySelectorAll('[data-month]').forEach(button=>button.onclick=()=>loadMonth(button.dataset.month));}
async function loadMonth(month){const target=view().querySelector('[data-month-detail]');target.innerHTML='<p>Loading scoresheet…</p>';try{const detail=(await api('/me/profile/months/'+encodeURIComponent(month))).profile.month;target.innerHTML=`<div class="profile-card" style="margin-top:14px"><h3>${h(monthLabel(month))} · Total ${h(detail.official_total??'—')}</h3><div class="profile-breakdown">${components(detail)}</div></div>`;}catch(error){target.innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}}
function renderCurrent(){if(state.profile.stale_projection){view().innerHTML='<p>The current daily view is awaiting an academy refresh. Your historical verified scores remain available.</p>';return;}const detail=state.profile.current_month_detail;if(!detail){view().innerHTML='<p>The current month is not active for this account.</p>';return;}view().innerHTML=`<div class="profile-card"><small>${h(monthLabel(detail.month))}</small><strong>Official total ${h(detail.official_total??'—')}</strong><div class="profile-breakdown">${components(detail)}</div></div><h3>Daily view</h3><div class="profile-days">${(detail.days||[]).map(day=>`<button class="profile-day ${day.future?'future':''} ${day.has_record?'has-record':''} ${!day.future&&day.has_record&&Number(day.recorded_total)>0?'score-positive':!day.future&&day.has_record&&Number(day.recorded_total)<0?'score-negative':''}" data-day="${h(day.date)}" ${day.future?'disabled':''}><strong>${h(Number(day.date.slice(-2)))}</strong><span>${day.recorded_total==null?'—':h(day.recorded_total)}</span></button>`).join('')}</div><p style="color:var(--muted);font-size:12px">Green = positive daily total · Red = negative daily total · Unfilled = zero or no score. Tap a day to review entries or send a tracked request to Admin.</p>`;view().querySelectorAll('[data-day]').forEach(button=>button.onclick=()=>openDay(button.dataset.day));}
function openDay(date){const day=state.profile.current_month_detail.days.find(row=>row.date===date);state.selectedDay=day;state.selectedRecipient=null;const entries=(day.entries||[]).map(entry=>`<div class="profile-entry"><strong>${h(entry.points)} points · ${h(entry.stars)} stars</strong><div>${h(entry.note||'No note')}</div></div>`).join('')||'<p>No score entry recorded for this day.</p>';const actions=[];if(day.actions?.request_missing_score)actions.push('<button class="profile-btn" data-request-kind="missing_score">Request score</button>');if(day.actions?.report_incorrect_entry)actions.push('<button class="profile-btn secondary" data-request-kind="incorrect_entry">Report incorrect entry</button>');if(day.actions?.request_transfer)actions.push('<button class="profile-btn secondary" data-request-kind="transfer_request">Request transfer</button>');sheet().innerHTML=`<div class="profile-sheet-head"><div><div class="profile-kicker">${h(date)}</div><h3>Day record</h3></div><button class="profile-close" data-close aria-label="Close">✕</button></div>${entries}<div class="profile-actions">${actions.join('')}</div><div data-day-form></div>`;sheet().querySelector('[data-close]').onclick=closeSheet;sheet().querySelectorAll('[data-request-kind]').forEach(button=>button.onclick=()=>renderRequestForm(button.dataset.requestKind));openSheet();}
function renderRequestForm(kind){const day=state.selectedDay,entries=day.entries||[];const entryField=kind==='incorrect_entry'?`<label>Entry<select name="entry">${entries.map((entry,index)=>`<option value="${index}">${h(entry.points)} points · ${h(entry.note)}</option>`).join('')}</select></label>`:'';const pointsField=kind==='missing_score'?'<label>Expected points, if known<input name="claimed_points" type="number" step="1"></label>':'';const transferFields=kind==='transfer_request'?'<label>Find recipient<input data-recipient-search placeholder="Roll number or name" autocomplete="off"></label><div class="profile-recipient-results" data-recipient-results></div><label>Transfer type<select name="transfer_type"><option value="points">Points</option><option value="stars">Stars</option></select></label><label>Amount<input name="amount" type="number" min="1" max="50" required></label>':'';sheet().querySelector('[data-day-form]').innerHTML=`<form class="profile-form" data-request-form><h3>${h(label(kind))}</h3>${entryField}${pointsField}${transferFields}<label>Explain the request<textarea name="message" maxlength="2000" required></textarea></label><button class="profile-btn" type="submit">Send to Admin</button></form>`;const form=sheet().querySelector('[data-request-form]');form.onsubmit=event=>submitRequest(event,kind);const search=form.querySelector('[data-recipient-search]');if(search)search.oninput=debounce(()=>searchRecipients(search.value),250);}
async function searchRecipients(query){const target=sheet().querySelector('[data-recipient-results]');state.selectedRecipient=null;if(query.trim().length<2){target.innerHTML='';return;}try{const data=await api('/me/transfer-recipients?q='+encodeURIComponent(query));target.innerHTML=data.recipients.map(row=>`<button type="button" class="profile-recipient" data-recipient="${h(row.student_id)}"><strong>${h(row.login_id)}</strong> · ${h(row.display_name)} · Class ${h(row.class_label||'—')}</button>`).join('')||'<small>No active recipient found.</small>';target.querySelectorAll('[data-recipient]').forEach(button=>button.onclick=()=>{state.selectedRecipient=data.recipients.find(row=>String(row.student_id)===button.dataset.recipient);target.querySelectorAll('button').forEach(item=>item.classList.toggle('selected',item===button));});}catch(error){target.innerHTML=`<small>${h(error.message)}</small>`;}}
async function submitRequest(event,kind){event.preventDefault();const form=event.currentTarget,data=new FormData(form),day=state.selectedDay,payload={kind,target_date:day.date,message:String(data.get('message')||''),client_request_id:crypto.randomUUID(),context_version:state.profile.current_month_detail.content_version};if(kind==='missing_score'&&data.get('claimed_points')!=='')payload.claimed_points=Number(data.get('claimed_points'));if(kind==='incorrect_entry'){const entry=day.entries[Number(data.get('entry'))];payload.target_entry_ref=entry.entry_ref;payload.target_entry_digest=entry.content_digest;}if(kind==='transfer_request'){if(!state.selectedRecipient){notice('Select a recipient first.',true);return;}payload.transfer={recipient_student_id:String(state.selectedRecipient.student_id),transfer_type:String(data.get('transfer_type')),amount:Number(data.get('amount'))};}const button=form.querySelector('button[type=submit]');button.disabled=true;try{await api('/me/requests',{method:'POST',body:JSON.stringify(payload)});closeSheet();state.view='requests';await loadRequests();notice('Request sent. Admin replies will appear here.');}catch(error){notice(error.message,true);button.disabled=false;}}
async function loadRequests(render=true){try{state.requestRows=(await api('/me/requests')).requests||[];if(render&&state.view==='requests')renderRequests();}catch(error){if(render)notice(error.message,true);}}
function renderRequests(){view().innerHTML=`<div class="profile-list">${state.requestRows.map(row=>`<button class="profile-request" data-request="${h(row.request_id)}"><span class="profile-request-head"><strong>${h(label(row.kind))} · ${h(row.target_date)}</strong><span class="profile-status">${h(label(row.status))}</span></span><small>${h(row.message)}</small></button>`).join('')||'<p>No requests yet. Tap a current-month day to create one.</p>'}</div>`;view().querySelectorAll('[data-request]').forEach(button=>button.onclick=()=>openRequest(button.dataset.request));}
async function openRequest(id){sheet().innerHTML='<div class="profile-sheet-head"><h3>Loading conversation…</h3><button class="profile-close" data-close aria-label="Close">✕</button></div>';sheet().querySelector('[data-close]').onclick=closeSheet;await openSheet();if(!root.querySelector('[data-profile-sheet].open'))return;try{const data=await api('/me/requests/'+id+'/events');if(!root.querySelector('[data-profile-sheet].open'))return;sheet().innerHTML=`<div class="profile-sheet-head"><h3>Request conversation</h3><button class="profile-close" data-close aria-label="Close">✕</button></div><div class="profile-timeline">${data.events.map(event=>`<div class="profile-event"><strong>${h(label(event.event_type))}</strong><div>${h(event.payload?.message||event.payload?.reason||'Status updated')}</div><small>${h(new Date(event.created_at).toLocaleString())} · ${h(event.actor_type)}</small></div>`).join('')}</div><form class="profile-form" data-message-form><label>Reply<textarea name="message" maxlength="2000" required></textarea></label><button class="profile-btn" type="submit">Send reply</button></form>`;sheet().querySelector('[data-close]').onclick=closeSheet;sheet().querySelector('[data-close]').focus();sheet().querySelector('[data-message-form]').onsubmit=event=>sendMessage(event,id);}catch(error){if(!root.querySelector('[data-profile-sheet].open'))return;sheet().innerHTML=`<div class="profile-alert error">${h(error.message)}</div><button class="profile-btn" data-close>Close</button>`;sheet().querySelector('[data-close]').onclick=closeSheet;sheet().querySelector('[data-close]').focus();}}
async function sendMessage(event,id){event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{await api('/me/requests/'+id+'/events',{method:'POST',body:JSON.stringify({message:new FormData(event.currentTarget).get('message'),client_message_id:crypto.randomUUID()})});await openRequest(id);await loadRequests(false);}catch(error){notice(error.message,true);button.disabled=false;}}
async function renderSessions(){view().innerHTML='<p>Loading signed-in devices…</p>';try{const data=await api('/auth/sessions');view().innerHTML=`<div class="profile-list">${data.sessions.map(row=>`<div class="profile-request"><span class="profile-request-head"><strong>${h(row.device_label||'Unnamed device')}</strong>${row.session_id===data.current_session_id?'<span class="profile-status">This device</span>':`<button class="profile-btn warn" data-revoke="${h(row.session_id)}">Sign out</button>`}</span><small>Signed in ${h(new Date(row.created_at).toLocaleString())}</small></div>`).join('')}</div>`;view().querySelectorAll('[data-revoke]').forEach(button=>button.onclick=()=>revokeSession(button.dataset.revoke));}catch(error){view().innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}}
async function revokeSession(id){try{await api('/auth/sessions/'+id,{method:'DELETE'});renderSessions();}catch(error){notice(error.message,true);}}
async function logout(){sessionGeneration++;try{if(!state.csrf)state.csrf=(await api('/auth/csrf')).csrf_token;await api('/auth/logout',{method:'POST'});}catch(error){notice('Sign out could not be confirmed. Please retry.',true);return false;}sessionStorage.removeItem(CSRF_KEY);state.csrf='';state.profile=null;state.workspace=null;state.account=null;state.requestRows=[];window.dispatchEvent(new CustomEvent('ea-portal-session',{detail:null}));stopDelivery();authScreen('login');return true;}
function profileVisible(){const panel=document.getElementById('myProfilePanel');return !document.hidden&&(!panel||panel.classList.contains('active'));}
function connectNotifications(){if(!deliveryActive||!profileVisible())return;try{const protocol=location.protocol==='https:'?'wss:':'ws:';const socket=new WebSocket(protocol+'//'+location.host+API+'/me/notifications/socket');state.socket=socket;socket.onopen=()=>{if(state.socket===socket){nextNotificationCheck=Date.now()+300000;pollNotifications();}};socket.onmessage=()=>pollNotifications();socket.onclose=()=>{if(state.socket!==socket||!deliveryActive)return;state.socket=null;nextNotificationCheck=Date.now()+60000;socketReconnect=setTimeout(connectNotifications,60000);};socket.onerror=()=>{try{socket.close();}catch{}};}catch{socketReconnect=setTimeout(connectNotifications,60000);}}
function startDelivery(){stopDelivery();if(!profileVisible()||Date.now()<quotaRetryAt)return;deliveryActive=true;nextNotificationCheck=Date.now()+60000;pollNotifications();state.poll=setInterval(()=>{if(profileVisible()&&Date.now()>=nextNotificationCheck){nextNotificationCheck=Date.now()+(state.socket?.readyState===1?300000:60000);pollNotifications();}},60000);connectNotifications();}
function stopDelivery(){deliveryActive=false;if(socketReconnect)clearTimeout(socketReconnect);socketReconnect=null;if(chatTimer){clearInterval(chatTimer);chatTimer=null;}if(state.poll)clearInterval(state.poll);state.poll=null;const socket=state.socket;state.socket=null;if(socket){socket.onclose=null;try{socket.close();}catch{}}}
async function pollNotifications(){if(notificationBusy||!profileVisible()||Date.now()<quotaRetryAt)return;notificationBusy=true;const generation=sessionGeneration,owner=String(state.account?.student_id||state.account?.staff_id||'');try{const key=CURSOR_KEY+':'+owner,after=sessionStorage.getItem(key)||'0',data=await api('/me/notifications?after='+encodeURIComponent(after));if(generation!==sessionGeneration)return;sessionStorage.setItem(key,String(data.cursor||after));if(data.notifications?.length){await loadRequests(false);if(state.view==='requests')renderRequests();notice(`${data.notifications.length} request update${data.notifications.length===1?'':'s'} received.`);}}catch{}finally{notificationBusy=false;}}
function resumeDelivery(){if(!profileVisible()){stopDelivery();return;}if(state.account&&(state.profile||state.account.kind==='staff')&&!deliveryActive){if(state.account.kind!=='staff')startDelivery();if(state.view==='chat')renderChat();}}
document.addEventListener('visibilitychange',resumeDelivery);
const profilePanel=document.getElementById('myProfilePanel');if(profilePanel)new MutationObserver(resumeDelivery).observe(profilePanel,{attributes:true,attributeFilter:['class']});
function debounce(fn,wait){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),wait);};}
function renderChat(){
  const rooms=state.workspace?.chat_rooms||[];
  if(!rooms.includes(chatRoom))chatRoom=rooms[0]||'general';
  view().innerHTML=`<div class="profile-chat-head"><div><h3>${h(chatRoom==='council'?'Student Council':'General Chat')}</h3><small>Messages are monitored under the academy rules.</small></div><div class="profile-actions">${rooms.map(room=>`<button type="button" class="profile-btn ${room===chatRoom?'':'secondary'}" data-chat-room="${h(room)}">${h(room==='council'?'Student Council':'General')}</button>`).join('')}</div></div><div class="profile-list" data-chat-messages aria-live="polite"><p>Loading messages…</p></div><div class="profile-alert" data-chat-error hidden></div>${state.account?.kind==='staff'?'':`<form class="profile-form" data-chat-form><label>Message<textarea name="message" maxlength="1500" required></textarea></label><button class="profile-btn" type="submit">Send message</button></form>`}`;
  view().querySelectorAll('[data-chat-room]').forEach(button=>button.onclick=()=>{chatRoom=button.dataset.chatRoom;chatRows=[];renderChat();});
  view().querySelector('[data-chat-form]')?.addEventListener('submit',sendChat);
  loadChat();
  if(!chatTimer)chatTimer=setInterval(()=>{if(state.view==='chat'&&profileVisible())loadChat();},60000);
}
async function loadChat(){
  if(chatBusy||!profileVisible()||Date.now()<quotaRetryAt)return;
  chatBusy=true;
  const room=chatRoom;
  try{
    const data=await api('/chat/'+room+'/messages');
    if(state.view!=='chat'||chatRoom!==room){chatBusy=false;return;}
    chatRows=data.messages||[];
    const target=view().querySelector('[data-chat-messages]');
    target.innerHTML=chatRows.map(row=>`<article class="profile-chat-message ${row.pinned?'pinned':''} ${row.highlighted?'highlighted':''}"><div class="profile-chat-meta"><strong>${h(row.login_id)}</strong><small>${h(new Date(row.created_at).toLocaleString())}</small>${row.pinned?'<span class="profile-status">Pinned</span>':''}${row.highlighted?'<span class="profile-status">Highlighted</span>':''}</div><p>${row.hidden?'<em>Message hidden by a moderator.</em>':h(row.body)}</p>${row.can_moderate?`<div class="profile-actions"><button type="button" class="profile-btn secondary" data-chat-action="hide" data-chat-id="${h(row.message_id)}">Hide</button>${data.moderator!=='co_leader'?`<button type="button" class="profile-btn secondary" data-chat-action="${row.pinned?'unpin':'pin'}" data-chat-id="${h(row.message_id)}">${row.pinned?'Unpin':'Pin'}</button><button type="button" class="profile-btn secondary" data-chat-action="${row.highlighted?'unhighlight':'highlight'}" data-chat-id="${h(row.message_id)}">${row.highlighted?'Remove highlight':'Highlight'}</button>`:''}<button type="button" class="profile-btn secondary" data-chat-restrict="${h(row.student_id)}">Restrict chat</button></div>`:''}</article>`).join('')||'<p>No messages yet.</p>';
    target.querySelectorAll('[data-chat-action]').forEach(button=>button.onclick=()=>moderateChat(button.dataset.chatId,button.dataset.chatAction));
    target.querySelectorAll('[data-chat-restrict]').forEach(button=>button.onclick=()=>restrictChat(button.dataset.chatRestrict));
    view().querySelector('[data-chat-error]').hidden=true;
  }catch(error){
    if(error.message==='database_daily_quota_exceeded'){serviceUnavailable(error);return;}
    if(state.view!=='chat'||chatRoom!==room||!view())return;
    const alert=view().querySelector('[data-chat-error]');alert.textContent=error.message;alert.hidden=false;
    if(error.status===403){view().querySelector('[data-chat-messages]').innerHTML='<p>Chat access is currently unavailable.</p>';view().querySelector('[data-chat-form]')?.remove();}
  }finally{chatBusy=false;if(chatRoom!==room&&state.view==='chat'&&profileVisible())setTimeout(loadChat,0);}
}
async function sendChat(event){
  event.preventDefault();
  const form=event.currentTarget,button=form.querySelector('button[type=submit]'),message=String(new FormData(form).get('message')||'').trim();
  if(!message)return;
  button.disabled=true;
  try{await api('/chat/'+chatRoom+'/messages',{method:'POST',body:JSON.stringify({message,client_message_id:crypto.randomUUID()})});form.reset();await loadChat();}
  catch(error){notice(error.message,true);}
  finally{button.disabled=false;}
}
async function moderateChat(id,action){
  const reason=action==='hide'?prompt('Reason for hiding this message:'):'';
  if(action==='hide'&&!reason)return;
  try{await api('/chat/'+chatRoom+'/messages/'+encodeURIComponent(id)+'/moderate',{method:'POST',body:JSON.stringify({action,reason})});await loadChat();}
  catch(error){notice(error.message,true);}
}
async function restrictChat(studentId){
  const duration=prompt('Restrict chat for how many hours? Leader: up to 24; Co-Leader: 1; Admin: up to 720.','1');
  if(duration===null)return;
  const reason=prompt('Reason for this chat restriction:');
  if(!reason)return;
  try{await api('/chat/restrictions',{method:'POST',body:JSON.stringify({student_id:studentId,duration_hours:Number(duration),reason})});notice('Chat restriction recorded.');await loadChat();}
  catch(error){notice(error.message,true);}
}
async function renderTransfers(){
  view().innerHTML='<h3>Points, stars and point banks</h3><div class="profile-grid profile-rules"><section class="profile-card"><h4>Points</h4><ul><li>Transfer 1–50 points at a time.</li><li>Transfers take effect after LAN processing; check the recorded status.</li><li>Another student must consent before their balance is debited.</li></ul></section><section class="profile-card"><h4>Stars</h4><ul><li>A sender can transfer up to 3 stars in 24 hours.</li><li>Repeat and reverse transfers between the same pair are locked for 24 hours.</li></ul></section><section class="profile-card"><h4>Point banks</h4><ul><li>Deposit your own points into an available bank.</li><li>Office holders award within their current jurisdiction and cannot award themselves.</li><li>Monthly grants and retained student deposits are tracked separately.</li><li>Bank transfers use points; each deposit or award is limited to 50.</li><li>Leadership shares a 500-point monthly grant; each group bank starts at 250, subject to approved quota changes.</li></ul></section></div><div data-transfer-workspace>Loading…</div>';
  try{
    const data=await api('/me/transfers');if(state.view!=='transfers')return;
    const target=view().querySelector('[data-transfer-workspace]');
    target.innerHTML=`<form class="profile-form" data-transfer-create><label>Operation<select name="operation"><option value="student_transfer">Student to student</option><option value="bank_deposit">Deposit my points in a bank</option><option value="bank_award">Award points from my office bank</option></select></label><label>Act as<select name="acting_assignment_id"><option value="">Myself</option>${postOptions()}</select></label><label data-transfer-sender>Sender<select name="sender_student_id"></select></label><label data-transfer-recipient>Recipient<select name="recipient_student_id" required></select></label><label data-transfer-bank hidden>Point bank<select name="bank_id">${(data.banks||[]).map(bank=>`<option value="${h(bank.bank_id)}">${h(bank.bank_id)} · ${h(bank.available)} available</option>`).join('')}</select></label><label>Type<select name="transfer_type"><option value="points">Points</option><option value="stars">Stars</option></select></label><label>Amount<input name="amount" type="number" min="1" max="50" step="1" required></label><label>Reason<textarea name="message" minlength="5" maxlength="500" required></textarea></label><button class="profile-btn" type="submit">Submit transfer</button></form><div class="profile-grid">${(data.banks||[]).map(bank=>`<div class="profile-card"><small>${h(bank.bank_id)} · ${h(monthLabel(bank.month))}</small><strong>${h(bank.available)} points</strong><p>Monthly grant remaining: ${h(bank.grant_remaining)}<br>Student deposits remaining: ${h(bank.deposits_remaining)}</p></div>`).join('')}</div><h3>Sender consent</h3>${(data.consents||[]).map(row=>`<article class="profile-card"><p>${h(row.transfer.amount)} ${h(row.transfer.transfer_type)} from student ${h(row.sender_student_id)} to student ${h(row.transfer.recipient_student_id)}</p><p>${h(row.message)}</p><small>${h(label(row.processing_status||row.status))}</small>${row.can_consent?`<div class="profile-actions"><button class="profile-btn" data-consent="${h(row.consent_id)}" data-accept="true">Consent to debit my balance</button><button class="profile-btn secondary" data-consent="${h(row.consent_id)}" data-accept="false">Decline</button></div>`:''}</article>`).join('')||'<p>No consent requests.</p>'}`;
    const form=target.querySelector('[data-transfer-create]'),acting=form.querySelector('[name=acting_assignment_id]'),op=form.querySelector('[name=operation]'),sender=form.querySelector('[name=sender_student_id]'),recipient=form.querySelector('[name=recipient_student_id]'),type=form.querySelector('[name=transfer_type]');
    const bankSelect=form.querySelector('[name=bank_id]'),submit=form.querySelector('button[type=submit]');
    const officeBank=post=>['leader','co_leader'].includes(post?.key)?'leadership':post?.key==='gr'?'group:'+post.scope.value:['pp','dpp'].includes(post?.key)?'party:'+post.scope.value:post?.key==='cr'?'class:'+post.scope.value:post?'office:'+post.key:'';
    const option=member=>`<option value="${h(member.student_id)}">${h(member.name||member.login_id)} · ${h(member.login_id||'')}</option>`;
    const own={student_id:state.account.student_id,login_id:state.account.login_id,name:'Myself'};
    const update=()=>{
      const area=(data.areas||[]).find(area=>area.post.assignment_id===acting.value),members=area?.members||[own,...(data.recipients||[])];
      sender.innerHTML=(acting.value?members:[own]).map(option).join('');sender.value=state.account.student_id;
      recipient.innerHTML=members.filter(member=>op.value==='bank_award'?member.student_id!==state.account.student_id:member.student_id!==sender.value).map(option).join('');
      form.querySelector('[data-transfer-sender]').hidden=op.value!=='student_transfer';form.querySelector('[data-transfer-recipient]').hidden=op.value==='bank_deposit';recipient.required=op.value!=='bank_deposit';form.querySelector('[data-transfer-bank]').hidden=op.value==='student_transfer';
      bankSelect.innerHTML=(data.banks||[]).filter(bank=>op.value!=='bank_award'||bank.bank_id===officeBank(area?.post)).map(bank=>`<option value="${h(bank.bank_id)}">${h(bank.bank_id)} · ${h(bank.available)} available</option>`).join('');
      bankSelect.required=op.value!=='student_transfer';submit.disabled=op.value==='bank_deposit'?!bankSelect.options.length:!recipient.options.length||(op.value==='bank_award'&&!bankSelect.options.length);
      type.disabled=op.value!=='student_transfer';if(type.disabled)type.value='points';form.querySelector('[name=amount]').max=type.value==='stars'?'3':'50';
      delete form.dataset.clientId;
    };
    acting.onchange=update;op.onchange=update;type.onchange=()=>{form.querySelector('[name=amount]').max=type.value==='stars'?'3':'50';delete form.dataset.clientId;};sender.onchange=()=>{const area=(data.areas||[]).find(area=>area.post.assignment_id===acting.value);recipient.innerHTML=(area?.members||data.recipients||[]).filter(member=>member.student_id!==sender.value).map(option).join('');delete form.dataset.clientId;};update();
    form.oninput=()=>{delete form.dataset.clientId;};
    form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]'),values=Object.fromEntries(new FormData(form));form.dataset.clientId ||= crypto.randomUUID();button.disabled=true;try{const result=await api('/me/transfers',{method:'POST',body:JSON.stringify({...values,transfer_type:type.value,amount:Number(values.amount),client_transfer_id:form.dataset.clientId})});await renderTransfers();notice(result.status==='awaiting_consent'?'Sent to the sender for consent.':'Transfer queued for the LAN. Track its outcome in My Requests.');}catch(error){notice(error.message,true);button.disabled=false;}};
    target.querySelectorAll('[data-consent]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/me/transfers/'+encodeURIComponent(button.dataset.consent)+'/consent',{method:'POST',body:JSON.stringify({accept:button.dataset.accept==='true'})});await renderTransfers();notice('Consent decision recorded.');}catch(error){notice(error.message,true);button.disabled=false;}});
  }catch(error){if(state.view==='transfers')view().querySelector('[data-transfer-workspace]').innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}
}
async function recordUi(action,target){if(!state.workspace?.audit_enabled||!state.account)return true;try{await api('/me/audit-events',{method:'POST',body:JSON.stringify({action,target})});return true;}catch(error){notice('The action could not be recorded. Please retry when the audit service is available.',true);return false;}}
function academyDestinations(){
  return [['tabHome','Home','home'],['tabScoreboard','Scoreboard','scoreboard'],['tabRanking','Ranking','ranking'],['tabParties','Party Standings','parties'],['tabChess','Chess Champion','chess'],['tabExcelResults','Excel Results','er/'],['tabExcelStudyNotes','Study Notes','sn/'],['tabInfo','Information','info'],['tabHelpdesk','Helpdesk','helpdesk']];
}
function renderAcademy(){
  view().innerHTML='<h3>Academy</h3><p>Open the existing academy tabs. Their current access requirements apply.</p><div class="profile-actions" data-academy-links></div>';
  const target=view().querySelector('[data-academy-links]');
  for(const [id,title,hash] of academyDestinations()){
    const local=document.getElementById(id);const button=document.createElement(local?'button':'a');button.className='profile-btn secondary';button.textContent=title;
    if(local){button.type='button';button.onclick=()=>local.click();}else{button.href='https://ea-tutorial-hub.pages.dev/#'+hash;}
    target.append(button);
  }
}
let partySummaryGeneration=0;
async function renderMyParty(){
  const generation=++partySummaryGeneration;
  const target=view();target.innerHTML='<h3>My Party</h3><p>Loading verified membership…</p>';
  try{
    const data=await api('/me/party-workspace');
    if(generation!==partySummaryGeneration||state.view!=='my-party'||!root.contains(target))return;
    if(data.membership_summary_available!==true||!Array.isArray(data.memberships)){
      target.innerHTML='<h3>My Party</h3><p>Your membership summary is not available in this portal version. Refresh after the next portal update; My Duties remains available.</p>';return;
    }
    const memberships=data.memberships,ids=new Set(memberships.map(row=>row.party_id));
    const assignments=(data.assignments||[]).filter(row=>String(row.recipient_student_id)===String(state.account?.student_id)&&ids.has(row.party_id));
    target.innerHTML=`<h3>My Party</h3><div class="profile-list">${memberships.map(row=>{
      const posts=(state.workspace?.posts||[]).filter(post=>post.scope?.kind==='party'&&post.scope.value===row.party_id);
      return `<article class="profile-card"><h4>${h(row.party_name||row.party_id)}</h4><p>Joined ${h(row.joined_on||'—')}</p><small>${h(posts.map(post=>post.label).join(' · ')||'Party member')}</small></article>`;
    }).join('')||'<p>No current party membership is recorded.</p>'}</div><p>Membership last verified ${h(data.verified_at?new Date(data.verified_at).toLocaleString():'—')}.</p><h3>My received party work</h3><div class="profile-list">${assignments.map(row=>`<article class="profile-card"><h4>${h(row.role)}</h4><p>${h(row.work)}</p><small>From ${h(row.issuer_label||'Party office')}${row.due_on?` · Due ${h(row.due_on)}`:''}</small></article>`).join('')||'<p>No party work is currently assigned to you.</p>'}</div>${document.getElementById('tabParties')?'<div class="profile-actions"><button type="button" class="profile-btn secondary" data-party-standings>Open Party Standings</button></div>':''}<div data-party-summaries></div><p>Party management remains in My Duties. Contributions use the current monthly standings formula.</p>`;
    const summaryTarget=target.querySelector('[data-party-summaries]');
    const summaries=(data.summaries||[]).filter(row=>ids.has(row.party_id));
    summaryTarget.innerHTML=summaries.map(row=>`<section class="profile-card"><h4>${h(memberships.find(m=>m.party_id===row.party_id)?.party_name||row.party_id)} · ${h(monthLabel(row.month))}</h4><div class="profile-party-officers"><div><small>PP</small>${row.pp.map(person=>h(person.name)+' · '+h(person.roll)).join('<br>')||'Vacant'}</div><div><small>DPP</small>${row.dpp.map(person=>h(person.name)+' · '+h(person.roll)).join('<br>')||'Vacant'}</div></div>${row.available?`<div class="profile-breakdown">${[['Party rank',row.rank],['Party total',row.total_score],['Party vote power',row.vote_power],['Members',row.member_count],['Your contribution',row.own_score],['Your vote power',row.own_vote_power]].map(([title,value])=>`<div><small>${h(title)}</small><strong>${h(value??'Unavailable')}</strong></div>`).join('')}</div>`:'<p>Statistics are unavailable until the academy resolves the membership records.</p>'}<small>Source revision ${h(data.source_revision)} · ${h(row.formula_version)}</small></section>`).join('')||'<p>Detailed party statistics await a refreshed academy projection.</p>';
    target.querySelector('[data-party-standings]')?.addEventListener('click',()=>document.getElementById('tabParties')?.click());
  }catch(error){
    if(generation!==partySummaryGeneration||state.view!=='my-party'||!root.contains(target))return;
    target.innerHTML='<h3>My Party</h3><div class="profile-alert error" role="status">Membership could not be verified. Please retry. This does not mean you have left your party.</div><button type="button" class="profile-btn secondary" data-party-retry>Retry</button>';
    target.querySelector('[data-party-retry]').onclick=renderMyParty;
  }
}
function decorateGovernanceTabs(){
  const nav=root.querySelector('.profile-subtabs');if(!nav)return;
  const add=(key,text)=>{if(nav.querySelector(`[data-view="${key}"]`))return;const button=document.createElement('button');button.dataset.view=key;button.textContent=text;button.onclick=()=>{state.view=key;renderView();};nav.append(button);};
  if(state.account?.kind!=='staff'&&state.workspace?.party_workspace_enabled)add('my-party','My Party');
  if(academyDestinations().length)add('academy','Academy');
  if(state.workspace?.audit_enabled&&state.account?.kind==='staff'&&state.workspace.identity?.role==='admin')add('audit','Audit history');
  if(state.workspace?.party_pacts_enabled)add('party-pacts',state.account?.kind==='staff'?'Party reviews':'Pacts & Membership');
}

function officeName(office){return office?.kind==='admin'?'Admin':office?.label?(office.label+(office.scope_name?' · '+office.scope_name:'')):label(office?.key||office?.kind||'Office');}
async function renderPartyPacts(){
  view().innerHTML='<h3>Party agreements</h3><p>Review the exact terms before accepting. Membership bonds last three calendar months from signing. Party pacts use their agreed end date; mergers require Admin review.</p><div data-party-content>Loading…</div>';
  try{
    const data=await api('/party-governance');if(state.view!=='party-pacts')return;
    const content=view().querySelector('[data-party-content]'),policy=data.policy.terms;
    content.innerHTML=`${data.admin?`<form class="profile-form" data-party-policy><h4>Future bond terms</h4><label>Early-exit points paid to party fund<input type="number" name="early_exit_points" min="1" max="10000" value="${h(policy.early_exit_points)}" required></label><label>Fallback stars to each PP and DPP<input type="number" name="fallback_stars_each" min="1" max="10" value="${h(policy.fallback_stars_each)}" required></label><label>Reason<textarea name="reason" minlength="10" required></textarea></label><small>Existing signed bonds retain their accepted terms.</small><button class="profile-btn">Save future terms</button></form>`:''}
      ${(data.memberships||[]).map((member,index)=>{const terms=member.bond?.terms||member.offer.terms;return `<article class="profile-card"><h4>${h(member.party_name)}</h4><p>${member.bond?'Signed':'Proposed'} membership bond: ${h(terms.starts_on)} to ${h(terms.ends_on)}.</p><p>Early exit: ${h(terms.early_exit_points)} points to the party fund. If points are insufficient: ${h(terms.fallback_stars_each)} star(s) each to the current PP and DPP. Missing recipients or insufficient stars require Admin resolution.</p><small>Terms reference: ${h(member.bond?.terms_digest||member.offer.terms_digest)}</small>${member.bond?'':`<form class="profile-form" data-bond-sign="${index}"><label><input type="checkbox" name="accept" required> I accept these membership dates and penalty terms.</label><button class="profile-btn">Sign membership bond</button></form>`}<form class="profile-form" data-party-exit="${index}"><label>Exit request reason<textarea name="reason" minlength="10" maxlength="2000" required></textarea></label><button class="profile-btn secondary">Request Admin exit review</button></form></article>`;}).join('')}
      ${data.posts?.length?`<form class="profile-form" data-pact-create><h4>Propose an inter-party pact</h4><label>Acting PP<select name="acting_assignment_id">${data.posts.map(post=>`<option value="${h(post.assignment_id)}">${h(data.peers.find(peer=>peer.party_id===post.scope.value)?.party_name||post.label)}</option>`).join('')}</select></label><label>Type<select name="kind"><option value="alliance">Alliance</option><option value="strategy">Strategy</option><option value="merger">Merger</option></select></label><fieldset><legend>Participating parties (include your own)</legend>${[...new Map(data.peers.map(peer=>[peer.party_id,peer])).values()].map(peer=>`<label><input type="checkbox" name="party_ids" value="${h(peer.party_id)}"> ${h(peer.party_name)}</label>`).join('')}</fieldset><label>Title<input name="title" minlength="3" maxlength="200" required></label><label>Agreed terms<textarea name="body" minlength="10" maxlength="4000" required></textarea></label><label>End date<input name="ends_on" type="date" required></label><label>Surviving party for a merger<select name="survivor_party_id"><option value="">Select for merger</option>${data.peers.map(peer=>`<option value="${h(peer.party_id)}">${h(peer.party_name)}</option>`).join('')}</select></label><button class="profile-btn">Offer pact for signatures</button></form>`:''}
      <h4>Pacts</h4>${(data.pacts||[]).map((pact,index)=>`<article class="profile-card"><h4>${h(pact.terms.title)} · ${h(label(pact.status))}</h4><p>${h(label(pact.terms.kind))} · ${h(pact.terms.parties.map(p=>p.party_name).join(', '))} · through ${h(pact.terms.ends_on)}</p><p>${h(pact.terms.body)}</p><small>Terms reference: ${h(pact.terms_digest)}</small><p>Signed by: ${h(pact.signatures.map(sig=>pact.terms.parties.find(p=>p.party_id===sig.party_id)?.party_name).join(', ')||'Awaiting signatures')}</p>${pact.effect?`<p>LAN: ${h(pact.effect.status)} ${h(pact.effect.error||'')}</p>`:''}${data.posts?.some(post=>pact.terms.parties.some(p=>p.party_id===post.scope.value))&&['offered','active','awaiting_admin'].includes(pact.status)?`<form class="profile-form" data-pact-action="${index}"><label>Acting PP<select name="acting_assignment_id">${data.posts.filter(post=>pact.terms.parties.some(p=>p.party_id===post.scope.value)).map(post=>`<option value="${h(post.assignment_id)}">${h(pact.terms.parties.find(p=>p.party_id===post.scope.value)?.party_name)}</option>`).join('')}</select></label><label>Action<select name="action">${pact.status==='offered'?'<option value="sign">Sign these terms</option>':''}<option value="terminate">Request mutual termination / withdraw unsigned offer</option></select></label><label><input type="checkbox" name="accept"> I accept the exact terms displayed above.</label><label>Reason for termination<textarea name="reason" maxlength="2000"></textarea></label><small>An active pact ends early only when every participating PP agrees.</small><button class="profile-btn">Record PP action</button></form>`:''}${data.admin&&pact.status==='awaiting_admin'?`<form class="profile-form" data-merger-review="${index}"><label>Merger decision<select name="decision"><option value="approved">Approve merger</option><option value="denied">Deny merger</option></select></label><label>Admin reason<textarea name="reason" minlength="10" required></textarea></label><p>Membership bonds retain their original end dates and penalty terms. Source party funds move to the surviving party.</p><button class="profile-btn">Record merger review</button></form>`:''}<div class="profile-timeline">${pact.events.map(e=>`<p>${h(label(e.event_type))} · ${h(e.actor_id)} · ${h(e.created_at)}</p>`).join('')}</div></article>`).join('')||'<p>No party pacts.</p>'}
      <h4>Exit requests</h4>${(data.exits||[]).map((exit,index)=>`<article class="profile-card"><strong>${h(exit.student_id)} · ${h(label(exit.status))}</strong><p>${h(exit.reason)}</p><p>${h(exit.effect?label(exit.effect.status)+(exit.effect.error?' · '+exit.effect.error:''):'Awaiting review or LAN processing')}</p>${data.admin&&exit.status==='pending'?`<form class="profile-form" data-exit-review="${index}"><label>Decision<select name="decision"><option value="approved">Approve exit and signed penalty</option><option value="denied">Deny exit</option></select></label><label>Admin reason<textarea name="reason" minlength="10" required></textarea></label><button class="profile-btn">Record exit review</button></form>`:''}</article>`).join('')||'<p>No exit requests.</p>'}`;
    const bind=(selector,build)=>content.querySelectorAll(selector).forEach(form=>{form.oninput=()=>delete form.dataset.clientId;form.onsubmit=async event=>{event.preventDefault();const values=new FormData(form),button=form.querySelector('button');form.dataset.clientId ||= crypto.randomUUID();button.disabled=true;try{const [path,payload]=build(form,values);await api(path,{method:'POST',body:JSON.stringify(payload)});await renderPartyPacts();notice('Party action recorded. Approved changes apply through the LAN.');}catch(error){notice(error.message,true);button.disabled=false;}};});
    bind('[data-bond-sign]',(form,v)=>{const member=data.memberships[Number(form.dataset.bondSign)];return ['/party-governance/bonds',{party_id:member.party_id,accept_terms:v.has('accept'),accepted_terms_digest:member.offer.terms_digest}];});
    bind('[data-party-exit]',(form,v)=>['/party-governance/exits',{party_id:data.memberships[Number(form.dataset.partyExit)].party_id,reason:v.get('reason'),client_exit_id:form.dataset.clientId}]);
    bind('[data-party-policy]',(form,v)=>['/admin/party-policy',{early_exit_points:Number(v.get('early_exit_points')),fallback_stars_each:Number(v.get('fallback_stars_each')),reason:v.get('reason'),expected_policy_digest:data.policy.digest}]);
    bind('[data-pact-create]',(form,v)=>['/party-governance/pacts',{...Object.fromEntries(v),party_ids:v.getAll('party_ids'),client_pact_id:form.dataset.clientId}]);
    bind('[data-pact-action]',(form,v)=>{const pact=data.pacts[Number(form.dataset.pactAction)];return ['/party-governance/pacts/'+pact.pact_id+'/'+v.get('action'),{acting_assignment_id:v.get('acting_assignment_id'),accept_terms:v.has('accept'),accepted_terms_digest:v.get('action')==='sign'?pact.terms_digest:'',reason:v.get('reason'),expected_version:pact.version,client_event_id:form.dataset.clientId}];});
    bind('[data-merger-review]',(form,v)=>{const pact=data.pacts[Number(form.dataset.mergerReview)];return ['/party-governance/pacts/'+pact.pact_id+'/review',{decision:v.get('decision'),reason:v.get('reason'),expected_version:pact.version,client_event_id:form.dataset.clientId}];});
    bind('[data-exit-review]',(form,v)=>['/party-governance/exits/'+data.exits[Number(form.dataset.exitReview)].exit_id+'/review',{decision:v.get('decision'),reason:v.get('reason')}]);
  }catch(error){if(state.view==='party-pacts')view().querySelector('[data-party-content]').textContent=error.message;}
}

async function renderAudit(){
  view().innerHTML='<h3>Portal audit history</h3><p>Recorded user actions, reads, authentication attempts and outcomes. Credentials and private message bodies are excluded from this view.</p><div data-audit-list>Loading…</div><button class="profile-btn secondary" data-audit-more hidden>Older events</button>';
  const load=async before=>{try{const data=await api('/admin/audit'+(before?'?before='+encodeURIComponent(before):''));if(state.view!=='audit')return;view().querySelector('[data-audit-list]').insertAdjacentHTML('beforeend',data.events.map(event=>`<article class="profile-entry"><strong>${h(event.action)} · ${h(event.outcome)}</strong><p>${h(event.actor_kind)} ${h(event.actor_id||'unidentified')} · ${h(event.method)} ${h(event.path)}</p><small>${h(event.created_at)} · ${h(event.phase)} · ${h(event.detail_code||'')} · request ${h(event.request_id)}</small></article>`).join(''));const more=view().querySelector('[data-audit-more]');more.hidden=!data.next_cursor;more.onclick=()=>load(data.next_cursor);}catch(error){notice(error.message,true);}};
  view().querySelector('[data-audit-list]').textContent='';await load();
}
function postOptions(keys){return (state.workspace?.posts||[]).filter(post=>!keys||keys.includes(post.key)).map(post=>`<option value="${h(post.assignment_id)}">${h(post.label)} · ${h(post.scope.kind==='academy'?'Academy':post.scope_name||post.scope.value)}</option>`).join('');}
function caseRoutingFields(){return `<label>Send as<select name="acting_assignment_id"><option value="">Myself</option>${postOptions()}</select></label><label>Issue channel<select name="topic" data-case-topic><option value="class">Class issue</option><option value="group">Group issue</option><option value="party">Own party issue</option><option value="academy">Academy issue</option>${state.workspace?.posts?.some(post=>post.key==='pp')?'<option value="party_diplomacy">Inter-party proposal as PP</option>':''}</select></label><label>Relevant office<select name="recipient" data-case-recipient><option value="">Automatic channel</option></select></label><small>Class: own CR → own GR → central office → Admin. Group and party cases start with their own representatives. Offices forward unresolved cases through the recorded channel.</small>`;}
async function renderCases(){
  const student=state.account?.kind==='student';
  view().innerHTML=`<h3>${student?'Proposals & Appeals':'Review Inbox'}</h3><p class="profile-duty-note">Track addressed proposals and appeals here. Approved quota proposals apply through the LAN; other decisions remain case records.</p>${student?`<form class="profile-form" data-case-create>${caseRoutingFields()}<label>Type<select name="kind"><option value="proposal">Proposal</option><option value="appeal">Appeal</option></select></label><label>Title<input name="title" minlength="3" maxlength="200" required></label><label>Details<textarea name="body" minlength="10" maxlength="4000" required></textarea></label><button class="profile-btn" type="submit">Submit case</button></form>`:''}<div class="profile-list" data-case-list><p>Loading cases…</p></div><div data-case-detail></div>`;
  view().querySelector('[data-case-create]')?.addEventListener('submit',submitCase);
  view().querySelector('[data-case-create]')?.addEventListener('input',event=>{delete event.currentTarget.dataset.clientId;});
  const recipientSelect=view().querySelector('[data-case-recipient]');
  if(recipientSelect){
    const topic=view().querySelector('[data-case-topic]'),acting=view().querySelector('[name=acting_assignment_id]');let revision=0;
    const refreshTargets=async()=>{const expected=++revision;recipientSelect.disabled=['class','group'].includes(topic.value);try{const data=await api('/cases/targets?topic='+encodeURIComponent(topic.value)+'&acting_assignment_id='+encodeURIComponent(acting.value));if(state.view==='cases'&&recipientSelect.isConnected&&expected===revision){recipientSelect.innerHTML='<option value="">Automatic channel</option>'+(data.targets||[]).map(target=>`<option value="${h(JSON.stringify(target))}">${h(target.label)} · ${h(target.scope.kind==='academy'?'Academy':target.scope_name||label(target.scope.kind)+' '+target.scope.value)}</option>`).join('');recipientSelect.required=topic.value==='party_diplomacy';if(recipientSelect.required)recipientSelect.querySelector('option[value=""]').textContent='Choose another party PP';}}catch(error){notice(error.message,true);}};
    topic.onchange=refreshTargets;acting.onchange=refreshTargets;refreshTargets();
  }
  try{const data=await api('/cases');if(state.view!=='cases')return;view().querySelector('[data-case-list]').innerHTML=(data.cases||[]).map(row=>`<button class="profile-request" data-case-id="${h(row.case_id)}"><span class="profile-request-head"><strong>${h(label(row.kind))} · ${h(row.title)}</strong><span class="profile-status">${h(label(row.status))}</span></span><small>${h(label(row.stage))} · ${h(new Date(row.updated_at).toLocaleString())}</small></button>`).join('')||'<p>No cases in your workspace.</p>';view().querySelectorAll('[data-case-id]').forEach(button=>button.onclick=()=>openCase(button.dataset.caseId));}
  catch(error){if(state.view==='cases')view().querySelector('[data-case-list]').innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}
}
async function submitCase(event){
  event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]'),data=new FormData(form);
  form.dataset.clientId ||= crypto.randomUUID();
  button.disabled=true;
  const chosen=data.get('recipient'),recipient=chosen==='student'?{kind:'student',login_id:data.get('recipient_login_id')}:chosen?JSON.parse(chosen):{};
  try{const result=await api('/cases',{method:'POST',body:JSON.stringify({kind:data.get('kind'),topic:data.get('topic'),title:data.get('title'),body:data.get('body'),direct_admin:data.has('direct_admin'),recipient,acting_assignment_id:data.get('acting_assignment_id')||'',client_case_id:form.dataset.clientId})});await renderCases();await openCase(result.case_id);notice('Case submitted. Its review history is visible below.');}
  catch(error){notice(error.message,true);button.disabled=false;}
}
async function openCase(id){
  const target=view().querySelector('[data-case-detail]');if(!target)return;target.innerHTML='<p>Loading case…</p>';
  try{
    const data=await api('/cases/'+encodeURIComponent(id));if(state.view!=='cases')return;
    const c=data.case,actor=c.viewer;
    let actions=[];
    if(!['approved','denied','withdrawn','resolved'].includes(c.status)){
      if(actor==='owner')actions=['message_added','withdrawn'];
      else if(actor==='recipient')actions=['message_added'];else if(actor==='channel_office'&&c.can_review)actions=['message_added','needs_information','resolved','channel_forwarded'];
      else if(actor==='leader'&&c.can_review)actions=['message_added','needs_information','forward_to_teacher','forward_to_admin'];
      else if(actor==='teacher'&&c.can_review)actions=['message_added','needs_information','recommended_approve','recommended_deny','forward_to_admin'];
      else if(actor==='admin')actions=c.stage==='admin'?['message_added','needs_information','approved','denied']:c.channel?.topic?['admin_takeover']:['forward_to_admin'];
    }
    target.innerHTML=`<div class="profile-card"><small>${h(label(c.kind))} · ${h(c.case_id)}</small><h3>${h(c.title)}</h3><p>${h(c.body)}</p><p>Status: ${h(label(c.status))} · With ${h(c.channel?.topic?officeName(c.recipient):label(c.stage))}</p>${c.channel?.route?`<p>Channel: ${h(c.channel.route.map(officeName).join(' → '))}</p>`:''}<div class="profile-timeline">${data.events.map(e=>`<div class="profile-event"><strong>${h(label(e.event_type))}</strong><div>${h(e.payload?.message||e.payload?.reason||'Status updated')}</div><small>${h(e.actor_label)} · ${h(new Date(e.created_at).toLocaleString())}</small></div>`).join('')}</div>${actions.length?`<form class="profile-form" data-case-action><label>Action<select name="event_type">${actions.map(a=>`<option value="${h(a)}">${h(label(a))}</option>`).join('')}</select></label><label>Message or reason<textarea name="text" maxlength="2000" required></textarea></label><label data-teacher-field hidden>Teacher<select name="teacher_staff_id" data-case-teachers></select></label><button class="profile-btn" type="submit">Record action</button></form>`:''}</div>`;
    if(c.quota_request?.kind){const q=c.quota_request;target.querySelector('.profile-card').insertAdjacentHTML('afterbegin',`<p><strong>Quota proposal:</strong> ${h(q.kind)} · ${h(q.target)} · ${h(q.amount)} ${h(q.unit)} · ${h(q.month)}</p><p>${data.effect?h(label(data.effect.status))+(data.effect.error?' · '+h(data.effect.error):''):c.status==='approved'?'Approved; awaiting LAN application.':'Pending Admin review.'}</p>`);}
    const form=target.querySelector('[data-case-action]');if(form){const select=form.querySelector('[name=event_type]'),teacherField=form.querySelector('[data-teacher-field]');select.onchange=async()=>{teacherField.hidden=select.value!=='forward_to_teacher';if(!teacherField.hidden){try{const data=await api('/cases/teachers');form.querySelector('[data-case-teachers]').innerHTML=data.teachers.map(t=>`<option value="${h(t.staff_id)}">${h(t.login_id)}</option>`).join('');}catch(error){notice(error.message,true);}}};form.oninput=()=>{delete form.dataset.clientId;};form.onsubmit=event=>submitCaseAction(event,c);}
  }catch(error){target.innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}
}
async function submitCaseAction(event,c){
  event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]'),data=new FormData(form),type=String(data.get('event_type')),value=String(data.get('text')||'').trim();
  form.dataset.clientId ||= crypto.randomUUID();
  button.disabled=true;
  try{await api('/cases/'+encodeURIComponent(c.case_id)+'/events',{method:'POST',body:JSON.stringify({event_type:type,expected_version:c.version,client_event_id:form.dataset.clientId,...(type==='message_added'?{message:value}:{reason:value}),...(type==='forward_to_teacher'?{teacher_staff_id:data.get('teacher_staff_id')}:{})})});await renderCases();await openCase(c.case_id);notice('Case history updated.');}
  catch(error){
    notice(error.message,true);button.disabled=false;
    if(error.message==='stale_case_version'){
      await openCase(c.case_id);
      const refreshed=view().querySelector('[data-case-action]');
      if(refreshed){
        refreshed.querySelector('[name=text]').value=value;
        const select=refreshed.querySelector('[name=event_type]');
        if([...select.options].some(option=>option.value===type)){select.value=type;await select.onchange?.();if(type==='forward_to_teacher')refreshed.querySelector('[name=teacher_staff_id]').value=String(data.get('teacher_staff_id')||'');}
        notice('The case changed. Your draft is preserved; review the updated history before submitting again.',true);
      }else{
        const draft=document.createElement('textarea');draft.readOnly=true;draft.value=value;draft.setAttribute('aria-label','Unsent case action draft');
        view().querySelector('[data-case-detail]')?.append(draft);
        notice('The case moved to another reviewer. Your unsent draft is shown below for copying.',true);
      }
    }
  }
}
async function renderInstructions(){
  view().innerHTML=`<h3>Instructions</h3><p>Read the instruction and acknowledge that you have seen it. Acknowledgement does not mark the work as completed.</p>${state.workspace?.can_issue_instructions?`<form class="profile-form" data-instruction-create>${state.account?.kind==='student'?`<label>Issue as<select name="acting_assignment_id" required>${postOptions()}</select></label>`:''}<label>Recipient roll / login ID<input name="recipient_login_id" maxlength="100" required></label><label>Title<input name="title" minlength="3" maxlength="200" required></label><label>Instruction<textarea name="body" minlength="10" maxlength="4000" required></textarea></label><label>Deadline, if applicable<input name="due_on" type="date"></label><button class="profile-btn" type="submit">Send instruction</button></form>`:''}<div class="profile-list" data-instructions><p>Loading instructions…</p></div>`;
  view().querySelector('[data-instruction-create]')?.addEventListener('submit',submitInstruction);
  view().querySelector('[data-instruction-create]')?.addEventListener('input',event=>{delete event.currentTarget.dataset.clientId;});
  try{
    const data=await api('/instructions');if(state.view!=='instructions')return;
    const target=view().querySelector('[data-instructions]');
    target.innerHTML=data.instructions.map(row=>`<article class="profile-card"><small>${h(row.received?'Received from '+row.issuer_label:'Sent to '+row.recipient_login_id)}</small><h4>${h(row.title)}</h4><p>${h(row.body)}</p><small>${h(new Date(row.created_at).toLocaleString())}${row.due_on?' · Due '+h(row.due_on):''}</small><p>${row.acknowledged_at?'Acknowledged '+h(new Date(row.acknowledged_at).toLocaleString()):'Awaiting acknowledgement'}</p>${row.received&&!row.acknowledged_at?`<button class="profile-btn" data-instruction-ack="${h(row.instruction_id)}">Acknowledge</button>`:''}</article>`).join('')||'<p>No instructions yet.</p>';
    target.querySelectorAll('[data-instruction-ack]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/instructions/'+encodeURIComponent(button.dataset.instructionAck)+'/acknowledge',{method:'POST'});await renderInstructions();}catch(error){notice(error.message,true);button.disabled=false;}});
  }catch(error){if(state.view==='instructions')view().querySelector('[data-instructions]').innerHTML=`<div class="profile-alert error">${h(error.message)}</div>`;}
}
async function submitInstruction(event){
  event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type=submit]'),data=new FormData(form);
  form.dataset.clientId ||= crypto.randomUUID();button.disabled=true;
  try{await api('/instructions',{method:'POST',body:JSON.stringify({...Object.fromEntries(data),client_instruction_id:form.dataset.clientId})});await renderInstructions();notice('Instruction sent to the named student.');}
  catch(error){notice(error.message,true);button.disabled=false;}
}
// This fragment is embedded in app.js so the isolated portal keeps one entry point.
let portraitMap=new Map();
function portraitHtml(studentId, name, broad=false){
  const id=portraitMap.get(String(studentId));
  const initials=String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  return `<span class="ea-portrait ${broad?'ea-portrait-broad':''}" aria-hidden="true">${id?`<img src="${API}/media/${h(id)}" alt="" loading="lazy">`:h(initials)}</span>`;
}
async function loadPortraits(){
  try{const data=await api('/media/portraits');portraitMap=new Map((data.portraits||[]).map(row=>[String(row.student_id),row.media_id]));}catch{portraitMap=new Map();}
}
async function preparePhoto(file, kind){
  if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw new Error('Choose a JPG, PNG or WebP photo up to 8 MB.');
  const bitmap=await createImageBitmap(file);
  try{
    if(bitmap.width*bitmap.height>24000000)throw new Error('Choose a smaller photo.');
    const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');
    const size=kind==='portrait'?512:1024, scale=Math.min(1,size/Math.max(bitmap.width,bitmap.height));
    canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
    ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);
    let encoded=canvas.toDataURL('image/jpeg',.8);
    for(const quality of [.65,.5,.35]){if(encoded.length<=192*1024*4/3+30)break;encoded=canvas.toDataURL('image/jpeg',quality);}
    if(encoded.length>192*1024*4/3+30)throw new Error('This photo is too detailed. Try a smaller image.');
    return encoded;
  }finally{bitmap.close();}
}
function photoForm(kind){return `<form class="profile-form" data-photo-upload="${kind}"><label>${kind==='portrait'?'New profile picture':'Photo'}<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label>${kind==='gallery'?'<label>Caption<textarea name="caption" maxlength="500" required></textarea></label>':'<input type="hidden" name="caption" value="">'}<p class="profile-photo-help">${kind==='gallery'?'Visible to signed-in academy users after Admin approval.':'Your profile picture appears across student displays after Admin approval.'}</p><button class="profile-btn" type="submit">Send photo for approval</button><p role="status" data-upload-status></p></form>`;}
function bindPhotoForms(){
  view().querySelectorAll('[data-photo-upload]').forEach(form=>{
    form.onchange=()=>{delete form.dataset.mediaId;};
    form.onsubmit=async event=>{
      event.preventDefault();const button=form.querySelector('button[type=submit]'),status=form.querySelector('[data-upload-status]');button.disabled=true;
      try{
        form.dataset.mediaId ||= crypto.randomUUID();
        status.textContent='Preparing your photo…';
        const image_data=await preparePhoto(form.querySelector('[name=photo]').files[0],form.dataset.photoUpload);
        await api('/me/media',{method:'POST',body:JSON.stringify({media_id:form.dataset.mediaId,kind:form.dataset.photoUpload,caption:form.querySelector('[name=caption]').value,image_data})});
        status.textContent='Saved. Awaiting Admin approval.';form.reset();delete form.dataset.mediaId;
      }catch(error){status.textContent=error.message;}finally{button.disabled=false;}
    };
  });
}
function renderPhotoSettings(){
  const o=state.profile.overview||{};
  view().innerHTML=`<h3>My profile picture</h3><section class="profile-card"><div class="profile-person">${portraitHtml(state.account.student_id,o.name,true)}<div><strong>${h(o.name)}</strong><p>Use a clear photo of yourself. Portraits have a circular frame and a soft depth effect.</p></div></div>${photoForm('portrait')}</section><h3>My submissions</h3><div data-photo-submissions>Loading…</div>`;
  bindPhotoForms();loadMyPhotos();
}
async function loadMyPhotos(){
  try{const data=await api('/me/media');const target=view()?.querySelector('[data-photo-submissions]');if(!target)return;
    target.innerHTML=(data.media||[]).map(row=>`<article class="profile-card"><div class="profile-person"><img class="profile-submission-photo" src="${API}/media/${h(row.media_id)}" alt="Your submitted photo" loading="lazy"><div><strong>${h(label(row.kind))} · ${h(label(row.status))}</strong><p>${h(row.caption)}</p>${row.review_reason?`<small>Admin: ${h(row.review_reason)}</small>`:''}</div></div></article>`).join('')||'<p>No photos submitted yet.</p>';
  }catch(error){const target=view()?.querySelector('[data-photo-submissions]');if(target)target.textContent=error.message;}
}
async function renderGallery(){
  view().innerHTML=`<h3>Student gallery</h3><p>Academy memories shared with signed-in students and staff.</p>${state.account?.kind!=='staff'?`<details class="profile-duty-compose"><summary>Post a photo with a caption</summary>${photoForm('gallery')}</details>`:''}<div class="profile-media-grid" data-gallery-list>Loading approved photos…</div><button class="profile-btn secondary" data-gallery-more hidden>Load more</button>${state.account?.kind!=='staff'?'<details class="profile-duty-compose"><summary>My submissions and review status</summary><div data-photo-submissions></div></details>':''}`;
  bindPhotoForms();loadMyPhotos();
  let before='',busy=false;const list=view().querySelector('[data-gallery-list]'),more=view().querySelector('[data-gallery-more]');
  const load=async()=>{if(busy)return;busy=true;more.disabled=true;try{const data=await api('/gallery'+(before?'?before='+encodeURIComponent(before):''));if(!list.isConnected)return;if(!before)list.innerHTML='';for(const row of data.media||[]){list.insertAdjacentHTML('beforeend',`<figure class="profile-card"><img src="${API}/media/${h(row.media_id)}" alt="${h(row.caption)}" loading="lazy"><figcaption><strong>${h(row.name||row.login_id||'Student')}</strong><p>${h(row.caption)}</p><small>${h(new Date(row.created_at).toLocaleDateString())}</small></figcaption></figure>`);}if(!list.childElementCount)list.textContent='No approved photos yet.';before=data.next_before;more.hidden=!before;}catch(error){if(list.isConnected)notice(error.message,true);}finally{busy=false;more.disabled=false;}};
  more.onclick=load;await load();
}
window.EA_PROFILE_APP={open:bootstrap,signOut:logout};if(location.hash.toLowerCase()==='#my-profile')bootstrap();else authScreen('login');
})();
